- README.md
- manifests/mod/wsgi.pp
- spec/classes/mod/wsgi_spec.rb
mod_wsgi must be compiled specifically for the python version in use. This change allows apache::mod::wsgi to take a specified package name and module name/path, in order to use a non-default python (i.e. the ones provided by the IUS Community repository, to use newer-than-default python versions on RHEL/CentOS). Behavior is unchanged if the params are left at their defaults.
> Modules-1458 mod_wsgi package and module name/path

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_access_log.erb
MODULES-1382: https://tickets.puppetlabs.com/browse/MODULES-1382
> MODULES-1382: support multiple access log directives

- manifests/mod/alias.pp
I've logged a JIRA ticket for this, please see 'MODULES-1692'.
> Quoted params to versioncmp in mod/alias.pp to avoid type error

- README.md
The README.md sample uses an array where a string is expected.
> Documentation fix: ssl_protocol expects a string, not an array.

- manifests/mod/proxy_connect.pp
- spec/classes/mod/proxy_connect_spec.rb
mod_proxy_connect was moved to own module since Apache >= 2.3.5.
AllowConnect directive won't work without this module on Ubuntu 14.04 or
Debian 8.
> MODULES-1684: Specify mod_proxy_connect module for Apache >= 2.3.5

- README.md
- templates/httpd.conf.erb
`use_optional_includes` should only be used for `additional_includes`,
otherwise things don't work.
> Fix for PR 845

- README.md
This was lost with #1007 (e8c565).
> ssl_protocol expects a string, not an array.

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
Create symlinks on all distros (not just Debian) when a separate $vhost_enable_dir is used. Without this a different $vhost_enable_dir as conf.d on centos does not create symlinks to enable vhosts.
> Symlinks on all distros

- README.md
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- templates/vhost/_rewrite.erb
- tests/vhost.pp
Here is the patch to support apache RewriteMap.
Since this is my first contribution/pull request every feedback is very wellcome.
> Add RewriteMap support

- README.md
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
This PR adds support for the ProxyErrorOverride directive. http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxyerroroverride
> add ProxyErrorOverride directive

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Allow multiple `Deny` directives in the same way as `Allow` already works, example:  
{ 'path' => '/var/ww/first',
'deny' => [ 'from 127.0.0.1', 'from 127.0.0.2', ],
},
> MODULES-1622: Allow multiple Deny directives in a directory

- manifests/mpm.pp
- manifests/params.pp
With this change I can use theforeman/puppet to setup a Puppet master under Passenger on FreeBSD.
> adjust params and mpm to recent FreeBSD packages

- manifests/params.pp
On CentOS 7 `/usr/lib64/httpd/modules/mod_ldap.so` is part of the `mod_ldap` RPM.
In previous versions it is part of the `httpd` RPM.
This PR installs `mod_ldap` on CentOS 7 systems.
> MODULES-1779 install package mod_ldap on CentOS 7

- README.md
- README.passenger.md
- manifests/mod/passenger.pp
- manifests/vhost.pp
- spec/classes/mod/passenger_spec.rb
- spec/defines/vhost_spec.rb
- templates/mod/passenger.conf.erb
- templates/vhost/_passenger.erb
(#1776) Add support for specifying PassengerAppEnv
either as a global setting to `apache::mod::passenger` or
per `apache::vhost`.
> Add support for Passenger's PassengerAppEnv setting

- manifests/vhost.pp
The scriptalias parameter is used in manifest/init.pp to setup the default vhosts.
However due to this bug $scriptalias from init.pp will never be set in the default vhost.
This propably need to be closely looked at, as this bugfix propably can have effects on other parts of the code.
This patch has been tested on Centos-7 and forge version of puppetlabs-apache 1.3.0
```puppet
class { '::apache': 
"default_confd_files"    =>  false,
"default_mods"            => false,
"default_vhost"            => true
}
```
> fix bug in scriptalias code that keeps scriptalias from beeing included in default vhost

- manifests/mod/event.pp
This should remove the warning and change the values to the defaults set by apache during the config check.
> AH00513: WARNING: MaxRequestWorkers of 256 is not an integer multiple of ThreadsPerChild of 25, decreasing to nearest multiple 250, for a maximum of 10 servers.
> Fixed default mpm_event config warning

- manifests/params.pp
- spec/classes/dev_spec.rb
(MODULES-1391) Correct Ubuntu Trusty mod_prefork package name
This module calls apache2-prefork-dev as the package
name for the mod_prefork module for all Debian-flavored Linuxes. However
Ubuntu 14.04 changes this to apache2-dev and makes apache2-prefork-dev
an alias.
The result is that calling this resource, even with the package
installed, always results in a package changed purged to present
message, as it's scanning dpkg for apache2-prefork-dev, finding the
package missing, and then installing the alias via apt.
> Fixes #880 - (MODULES-1391) Correct Ubuntu Trusty mod_prefork package name

- manifests/params.pp
This module calls apache2-prefork-dev as the package
name for the mod_prefork module for all Debian-flavored Linuxes. However
Ubuntu 14.04 changes this to apache2-dev and makes apache2-prefork-dev
an alias.
The result is that calling this resource, even with the package
installed, always results in a package changed purged to present
message, as it's scanning dpkg for apache2-prefork-dev, finding the
package missing, and then installing the alias via apt.
Relates to 25be287baf for the Ubuntu part
> (#1391) Correct Debian jessie mod_prefork dev package name

- README.md
The README.md file contains inaccurate information for the ssl_protocol setting. It has it listed as a string, but in reality an array is expected.
I have also fixed some contradiction on the ssl_protocol and ssl_cipher definitions.
> Corrected error in documentation for ssl_protocol and ssl_cipher.

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
See https://tickets.puppetlabs.com/browse/MODULES-1784 for more information.
Basically if you specify allow, deny, order or satisfy on a system running Apache 2.4, those options get silently dropped. 
With this pull request those manifests would fail and alert the user that they are not using supported options.
Feedback very much welcome.
I tried to solve this in the manifest but failed since $directories can be an array of hashes and I found no way to check for the existence of a key in such a construct.
> MODULES-1784 check for deprecated options and fail when they are unsupported

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
> add proper array support for require

- manifests/default_mods.pp
mod_filter gets included in a few places, and when some of them include and other instantiate, we end up with duplicate resources.
> include mod_filter when needed instead of instantiating it

- manifests/init.pp
- spec/classes/apache_spec.rb
As the code is now, if you set default_vhost or default_ssl_vhost to
false, the docroot directory will still be managed, but you will be
unable to set non-default ownership. Set manage_docroot to the value of
default*_vhost in the vhost resource declarations.
> Don't manage docroot when default vhosts are disabled

- README.md
Following the quickstart doesn't work in older Ruby version (like the default version on RHEL 6 systems)
```
$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Using rake 10.4.2
Using CFPropertyList 2.3.0
Gem::InstallError: i18n requires Ruby version >= 1.9.3.
An error occurred while installing i18n (0.7.0), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.7.0'` succeeds before bundling.
```
You need this command instead:
```
$ bundle install --without system_tests
```
> Documentation: fix Quickstart instructions for Ruby 1.8.7 (Red Hat)

- spec/acceptance/vhost_spec.rb
Minor change, fallbackresource incorrectly typed as fallbackresouce
> Fix typo in fallbackresource

- README.md
- manifests/init.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
Please make sure to review the test, I'm not that familiar with rspec.
> Adds the AddDefaultCharset option

- README.md
- manifests/balancer.pp
- manifests/custom_config.pp
- manifests/mod/auth_cas.pp
- spec/defines/custom_config_spec.rb
(#MODULES-1829) Fix resources that notify Service[httpd]
With the introduction of the service_manage bool, the Service[httpd]
class will not be part of the catalog if false. However there are still
some resources which notify Service[httpd] instead of the wrapper
Apache::Service class and these choke on undefined Service[httpd]
resource if service_manage is false.
> Ensure resources notify Apache::Service class

- README.md
Pretty self-explanatory, this is just a really minor documentation typo fix.
> Added missing comma in the aliases example section

- manifests/mod/passenger.pp
- manifests/params.pp
- spec/classes/mod/passenger_spec.rb
By giving mod_passenger a lower priority, mod_proxy will be loaded before mod_passenger, allowing a single vhost to direct certain requests using mod_proxy and direct the others to mod_passenger.
Use case: puppetmaster where the CA requests are proxied to a single server (without the need to configure the agents for different servers).
> give a lower priority to mod_passenger

- README.md
- manifests/init.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
This setting is only valid on Apache httpd 2.2 (and possibly lower)
Please make sure to review the test extensively, I may have done something wrong about the position I placed that test.
> Apache: allow setting the default type

- manifests/mod/passenger.pp
- spec/classes/mod/passenger_spec.rb
On Red Hat systems it was entirely possible to have the path for 'passenger_package.conf' file equal to that of the 'passenger.conf' file, causing an error. This was only the case when the '$passenger_conf_package_file' variable was not set (the default behaviour).
It was due to be removed anyway.
> Remove Debian workaround as it broke Red Hat systems

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
This patch adds support to set variables using 'SetEnv' inside proxy
locations. This is needed to support some backends that don't properly
support HTTP/1.1, as it allows a fallback by the Apache httpd server.
For details see [1] (Apache httpd documentation) and [2] (use case).
[1] http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#envsettings
[2] https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Apache
> Allow setting environment variables inside the proxy locations

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
This would require more tests, although due to how the tests for the normal ProxyPass directive are written, they match ProxyPassMatch as well, making it a bit more difficult.
> Apache: add support for the ProxyPassMatch directive

- README.md
Use a code block for the commands so they are displayed properly on
GitHub.
> Documentation: style fix

- spec/acceptance/mod_suphp_spec.rb
It works fine on all the ubuntus. It's clearly ok. I don't know why
debian 7 does this.
> Debian 7 is very inconsistent with mod_suphp

- README.md
- manifests/mod/ssl.pp
- spec/defines/vhost_spec.rb
- templates/mod/ssl.conf.erb
SSLSessionCacheTimeout, SSLCryptoDevice and SSLHonorCipherOrder are currently hardcoded in ssl.conf.erb.
This PR allows those to be overridden via parameters to apache::mod::ssl.
This will also fix https://tickets.puppetlabs.com/browse/MODULES-1851.
> Allow settings to be overridden as parameters to apache::mod::ssl

- README.md
- manifests/mod/geoip.pp
- manifests/params.pp
- templates/mod/geoip.conf.erb
- templates/vhost/_directories.erb
This adds support for mod_geoip.
I've tested it on CentOS 6 and 7.
There is one problem with this: if you want to set `GeoIPEnable` in a `directories` parameter you must declare the class `apache::mod::geoip` yourself.  
As the `directories` parameter can be an array of hashes I cannot check for the value of `geoip_enable` here:  
```puppet
apache::vhost { 'first.example.com':
docroot     => '/var/www/first',
{ path         => '/var/www/first',
geoip_enable => 'On',
},
],
}
```
And because of this, I cannot automatically include it.
> MODULES-1789 add initial mod_geoip support

- templates/vhost/_proxy.erb
This fix should allow people using multiple env_var because each var being set needs to be on it's own line.
> Fixed setting multiple env_var in a location block for proxy pass.

- manifests/mod/userdir.pp
- templates/mod/userdir.conf.erb
Always have `Indexes` enabled for `mod_userdir` seems wrong, so this pull request makes it configurable.
> Make Options directive configurable for mod userdir

- templates/mod/userdir.conf.erb
After fixing the permission directives for Apache 2.4 in 460775670a, the userdirs were not accessible anymore because of `Require all denied`.
> allow acess to userdirs again

- spec/classes/mod/remoteip_spec.rb
We updated the rspec-puppet tests, then merged e0255bd,which assumed
rspec-puppet 1. This patch updates the newly merged tests for the
remoteip mod.
> Fix remoteip unit test for rspec-puppet 2

- manifests/mod/proxy_connect.pp
- spec/classes/mod/proxy_connect_spec.rb
As discussed in MODULES-1874, the proxy_connect module exists since Apache 2.2, so there is no reason to restrict it to Apache >= 2.4.
[MODULES-1874](https://tickets.puppetlabs.com/browse/MODULES-1874) was closed as Fixed a week ago, but the problem is still present in master and I couldn't find a PR that fixes this.
> (MODULES-1874) Fix proxy_connect module on apache >= 2.2

- README.md
- manifests/init.pp
- manifests/mod.pp
- manifests/mod/wsgi.pp
- manifests/mpm.pp
In conjunction with `${apache::apache_version}` it is sometimes required to also change `$lib_path` to a non-default location. This patch introduces `lib_path` as a new parameter.
> make $lib_path configurable

- lib/puppet/parser/functions/validate_apache_log_level.rb
- manifests/init.pp
- manifests/vhost.pp
- spec/unit/puppet/parser/functions/validate_apache_log_level.rb
this request came out of discussion on "log_level ^ and $ removed so that log_levels like info ssl:debug are allowed #1089"
added validate_apache_log_level function to apply same test to both apache class and vhost - trace levels also supported
still todo is think about supporting log_level checking in directories
> unify log_level checking and allow trace1-8 levels

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
Hi,
version 1.4 started to support proxy_pass_match. The featrue seems not to be fully implemented. The variable is now known by the module but does not change anything except loading of the mod_proxy httpd module. I changed the vhost.pp so that proxy_pass_match will make use of the proxy template.
Kind regards,
Matthias
> Change proxy_pass_match to use the proxy template

- spec/acceptance/vhost_spec.rb
The beaker-rspec contains matcher does not understand "+" in the
context of checking whether a string is contained in a file resource
(though it does seem to understand "\s" just fine), which was causing
acceptance test failures. Since we know the exact string to expect we
just remove the regular expression bits.
> Use string instead, not regex, for file test

- metadata.json
PE < 3.7.0 binds to puppetlabs-concat 1.0.x, which is incompatible with
the vhost rewrite that was added in puppetlabs-apache 1.2.0.
> Update PE dependency in 1.4.x

- README.md
- manifests/init.pp
- manifests/service.pp
- spec/classes/service_spec.rb
Adds a new parameter to apache and apache::service to
permit restart paramter to the httpd service to be set.
For instance this allows to a restart to be configured
as apachectl graceful for instance.
Fixes https://tickets.puppetlabs.com/browse/MODULES-1971
the change is fully backwards compatible.
> (#1971) new $service_restart parameter to influence httpd.

- manifests/version.pp
Fixes https://tickets.puppetlabs.com/browse/MODULES-1937 by identifying Amazon Linux before checking any version numbers.
I'm afraid I'm not able to add tests for this.
> MODULES-1937: fixes mismatching of Apache version on Amazon Linux

- README.md
The `README` doesn't document the presence of the `user` and `group` parameters for `::apache`, though they are referenced by `manage_user` and `manage_group`. This change provides that documentation, and includes a pointer to `manage_user` and `manage_group` respectively.
> Add user and group directives to Class: apache documentation

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
Even when default_ssl_vhosts is false, the value of scriptalias gets defined and vhost resource includes  the alias module. To avoid that we need to check the condition if ensure => present before including the alias module.
> check if ensure present before including alias module

- README.md
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
if an admin overrides one of the pre-existing formats, do not offload
that to httpd: check for it, and replace it at configuration
generation time.
> Do not offload overriding LogFormats to httpd

- .fixtures.yml
- manifests/balancer.pp
- manifests/balancermember.pp
- manifests/init.pp
- manifests/listen.pp
- manifests/namevirtualhost.pp
- metadata.json
- spec/defines/vhost_spec.rb
2.0.0 is compatible with current 1.x usage, so permit either 1.x or 2.x
to satisfy the concat dependency.  Move all ensure parameters from
concat::fragment to concat itself.
> Support puppetlabs-concat 2.x

- .fixtures.yml
- manifests/balancer.pp
- manifests/balancermember.pp
- manifests/init.pp
- manifests/listen.pp
- manifests/namevirtualhost.pp
- metadata.json
- spec/defines/vhost_spec.rb
We're running into https://tickets.puppetlabs.com/browse/MODULES-2104 which affects subscribe and notify. As such we need to stick with concat 1.x.
> Revert "Support puppetlabs-concat 2.x"

- Gemfile
- spec/spec_helper_acceptance.rb
As of 0.1.0 it doesn't work with puppet-agent because the paths have to
be updated.
> Add the helper to install puppet/pe/puppet-agent

- README.md
- manifests/mod/ssl.pp
- manifests/vhost.pp
- spec/classes/mod/ssl_spec.rb
- spec/defines/vhost_spec.rb
- templates/mod/ssl.conf.erb
- templates/vhost/_ssl.erb
Being able to set SSLOpenSSLConfCmd e. g. allows for setting DHParameters in order to protect against [Logjam attack](https://weakdh.org).
> Add ssl_openssl_conf_cmd param (apache::mod::ssl and apache::vhost)

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
The _proxy.erb partial template must also be inserted when only @proxy_dest_match
or @proxy_dest_match are set.
> Fix test condition for proxy directives.

- spec/acceptance/mod_security_spec.rb
While running AIO tests on RHEL6, the httpd service takes a bit longer
to init. Since Apache init scripts return and completes init asynchronously
this causes tests to fail. Adding a short sleep here to wait for the service
to init compensates for the slower init.
> fixes timing of mod_security tests for aio

- manifests/mod/alias.pp
- manifests/params.pp
It is not always that we want Alias /icons in our config, but right now if the alias mod gets pulled in there is no way around that. This commit fixes that.
> add possibility to set icons_path to false so no alias will be set for it

- manifests/vhost.pp
extended regex for suexec users/groups to accept '-' additionally to word characters
> we also want to have groups with '-' like vhost-users

- README.md
- manifests/mod/security.pp
- manifests/params.pp
- templates/mod/security.conf.erb
> [#puppethack] Adding ability to enable/disable the secruleengine through a parameter

- templates/vhost/_proxy.erb
Fix _proxy.erb to put multiple SetEnv directives on separate lines for ProxyMatch blocks.  This was already fixed for plain ProxyPass blocks.
> Fix _proxy.erb for SetEnv within ProxyMatch.

- README.md
- README.passenger.md
Massive reorg and style edit, bringing the way we present classes,
defines, and parameters in line with our established styles. Documents
several undocumented parameters and default values, especially in Apache
module classes.
This work is incomplete; there are many more undocumented parameters and
more style and formatting consistency issues to resolve.
> Apache readme reorganization.

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
I was testing with debian jessie connecting to a puppetmaster 3.7.3-1 + hiera and apache/templates/vhost/_additional_includes.erb was reporting @use_optional_includes as undef.
> Adding use_optional_includes parameter to vhost define.

- manifests/params.pp
Hello
The "libapache2-mod-geoip" is missing on Debian systems.
This PR is fixing this issue.
Regards
> Fix: missing package for mod_geoip on Debian systems

- templates/mod/userdir.conf.erb
The UserDir directive in templates/mod/userdir.conf.erb should probably match the [directory stanza](https://github.com/puppetlabs/puppetlabs-apache/blob/master/templates/mod/userdir.conf.erb#L7) directly below it.
We were setting `home` as /var/home and getting inconsistent results since it wasn't actually being passed to UserDir. Changing this seemed to fix our issue.
> Include full path for UserDir directive

- manifests/mod/cgid.pp
Before this, attempting to include `apache::mod::cgid` when using the event MPM
raised the following error:
`Could not find resource 'Class[Apache::Mod::Worker]' for relationship on 'Class[Apache::Mod::Cgid]'`
> Fix apache::mod::cgid so it can be used with the event MPM

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
`mod::alias` should be included when `aliases` is set, otherwise Apache fails to start.
I've added a simple rspec test around this as well, though it seems to stand out from the other tests around vhosts. Ideally acceptance tests would catch things like this as well, but a separate test for each parameter seems like a rather large undertaking (though I'm happy too look at adding one for this case if desired).
> mod::alias should be included when the aliases parameter is used

- README.md
- manifests/default_mods.pp
- manifests/init.pp
- manifests/params.pp
default_mods.pp --> added use_systemd option, if running a custom build of apache on
centos7, user modifiable boolean option provided
init.pp --> added pidfile and use_systemd option both of which go to params.pp and allow
these values to be set in hiera. changed all osfamily choices for conf_dir
to draw values from the $pidfile variable.
params.pp --> added $use_systemd, by default set to true to mimic original behaviour.
added $pidfile, set to mimic exact same behaviour as used in init.pp,
except now user changeable via hiera.
> Add support for user modifiable installation of mod_systemd and pidfile locations:

- README.md
- manifests/mod/auth_mellon.pp
- manifests/params.pp
- spec/classes/mod/auth_mellon_spec.rb
- templates/mod/auth_mellon.conf.erb
- templates/vhost/_directories.erb
mod_auth_melon is an authentication module
for apache. Configurations such as the following
are now supported.
```puppet
class{'apache':
default_mods        => false,
default_confd_files => false,
default_vhost       => false,
}
class{'apache::mod::auth_mellon':
mellon_cache_size => 101
}
apache::vhost{$::fqdn:
docroot => '/var/www/html',
port    => 443,
ssl     => true,
ssl_key => "/etc/certs/${::fqdn}.key",
ssl_cert => "/etc/certs/${::fqdn}.cert",
{  path           => '/',
provider       => 'directory',
mellon_enable  => 'info',
mellon_merge_env_vars => 'On',
mellon_endpoint_path => '/mellon',
mellon_sp_private_key_file => "/etc/certs/${::fqdn}.key",
mellon_sp_cert_file => "/etc/certs/${::fqdn}.cert",
mellon_idp_metadata_file => …
```
> (MODULES-2458) Support for mod_auth_mellon.

- manifests/mod/authz_default.pp
Having it in the server config will prevent the server from starting as the module file cannot be found.
> Catch that mod_authz_default has been removed in Apache 2.4

- README.md
- manifests/vhost.pp
- templates/vhost/_ssl.erb
Add support for the Apache SSLProxyMachineCertificateFile directive which allows the apache reverse proxy to use a client certificate to authenticate to its upstream.
> Client auth for reverse proxy

- README.md
- manifests/mod/deflate.pp
Hello,
How can I customize the "types" of "deflate " while using " default_mods " ?
I need to deflate "application/json".
JSON is a common text resource types on the web which should be served with HTTP compression:
https://zoompf.com/blog/2012/02/lose-the-wait-http-compression
Thks
> Deflate "application/json" by default

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_auth_kerb.erb
https://tickets.puppetlabs.com/browse/MODULES-2419
The following kerberos parameters can be set within
a vhost.
KrbMethodNegotiate
KrbMethodK5Passwd
KrbAuthoritative
KrbAuthRealms
Krb5Keytab
KrbLocalUserMapping
Reference for mod_auth_kerb:
http://modauthkerb.sourceforge.net/configure.html
https://bugzilla.redhat.com/show_bug.cgi?id=970678
> (MODULES-2419) - Add mod_auth_kerb parameters to vhost

- manifests/package.pp
Was unsetting 'MPM_PERFORK', so 'MPM_PREFORK' would not have been
unset correctly.
> Fix typo of MPM_PREFORK for FreeBSD package install

- README.md
Fix error regarding the shib_request_settings setting for a vhost directory. Also, fix value of said attribute to a hash instead of a string.
> Fix erroneous example in README.md

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_limits.erb
Support setting of LimitRequestFieldSize on a vhost.
```puppet
apache::vhost{'foo':
limit_request_field_size => 1234
}
```
by default value is unset.
http://httpd.apache.org/docs/2.4/mod/core.html#limitrequestfieldsize
https://tickets.puppetlabs.com/browse/MODULES-2616
> (MODULES-2616) Optionally set LimitRequestFieldSize on an apache::vhost

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
e.g
```puppet
apache::vhost{'abc.example.org':
{ path              => '/path/to/filtered',
set_output_filter => 'puppetdb-filter',
},
],
}
```
* https://tickets.puppetlabs.com/browse/MODULES-2649
* http://httpd.apache.org/docs/current/mod/core.html#setoutputfilter
> (MODULES-2649) Allow SetOutputFilter to be set on a directory.

- README.md
- manifests/default_mods.pp
- manifests/mod/ext_filter.pp
- spec/classes/mod/ext_filter_spec.rb
- templates/mod/ext_filter.conf.erb
- templates/vhost/_directories.erb
Permits the
* ExtFilterDefine to be set multiple times on a server.
* ExtFilterOptions to be set on a directory context.
```puppet
class{'apache':
default_mods => false,
directories  => [
{ path               => '/var/www/filter',
ext_filter_options => 'LogStderr Onfail=abort',
},
],
}
class{'apache::mod::ext_filter':
ext_filter_define => { 'slowdown'       => 'mode=output cmd=/bin/cat preservescontentlength',
'puppetdb-strip' => 'mode=output outtype=application/json cmd="pdb-resource-filter"'
},
}
```
> (MODULES-2647) Optinally set parameters for mod_ext_filter module

- README.md
- manifests/mod/ssl.pp
ref https://community.qualys.com/blogs/securitylabs/2013/09/17/updated-ssltls-deployment-best-practices-deprecate-rc4 - usage will downgrade the SSL rating from A to B on their rating service at https://www.ssllabs.com/ssltest/
> RC4 is deprecated

- manifests/custom_config.pp
- manifests/init.pp
- manifests/mod.pp
- spec/defines/custom_config_spec.rb
When setting up a new machine from scratch and adding some `::apache::custom_config`s, I see these:
```
Info: /Stage[main]/Profiles::Apache/Apache::Custom_config[my-permissions-generic]/File[apache_my-permissions-generic]: Scheduling refresh of Exec[service notify for my-permissions-generic]
Info: /Stage[main]/Profiles::Apache/Apache::Custom_config[my-permissions-generic]/File[apache_my-permissions-generic]: Scheduling refresh of Exec[remove my-permissions-generic if invalid]
Notice: /Stage[main]/Profiles::Apache/Apache::Custom_config[my-permissions-generic]/Exec[service notify for my-permissions-generic]/returns: AH00526: Syntax error on line 22 of /etc/apache2/sites-enabled/000-some.site
Notice: /Stage[main]/Profiles::Apache/Apache::Custom_config[my-permissions-generic]/Exec[service …
```
> Install all modules before adding custom configs

- README.md
- spec/acceptance/vhost_spec.rb
- templates/vhost/_ssl.erb
https://tickets.puppetlabs.com/browse/MODULES-2655
> Change SSLProtocol in apache::vhost to be space separated

- README.md
- manifests/vhost.pp
- templates/vhost/_docroot.erb
This is a single commit version of a similar pull request.
Ignoring the document root requires setting both docroot and manage_docroot to false.
> (MODULES-2120) Allow empty docroot

- README.md
- manifests/init.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
as addition to the [RewriteMap](https://github.com/puppetlabs/puppetlabs-apache/pull/900) feature i've added the option to define a [RewriteLock](http://httpd.apache.org/docs/2.2/mod/mod_rewrite.html#RewriteLock) for apache version <= 2.2 which is considered best practice when using a RewriteMap of type [prg](https://httpd.apache.org/docs/2.2/rewrite/rewritemap.html#prg)
> RewriteLock support

- manifests/init.pp
- spec/acceptance/custom_config_spec.rb
- spec/classes/apache_spec.rb
The httpd.conf.erb template explicitly includes the $ports_file, but the resource that uses that
template doesn't have a dependency on $ports_file. This means it's possible for a declaration of the
apache::custom_config resource to get run between when $conf_file is written and $ports_file is
written. This will cause syntax verification via "apachectl -t" to always fail, causing the
custom_config to be removed if the $verify_config flag is set to "true". Example:
==> ops: Notice: /Stage[main]/Jci_nagios::Server/Apache::Custom_config[cgid]/Exec[service notify for cgid]/returns: httpd: Syntax error on line 37 of /etc/httpd/conf/httpd.conf: Could not open configuration file /etc/httpd/conf/ports.conf: No such file or directory
==> ops: Error: …
> Fix ordering issue with conf_file and ports_file

- spec/acceptance/custom_config_spec.rb
this is in relation to the fix from #1230 
PE tests would fail because they have a slightly different error message.
> reduce constraints on regex to fix pe tests

- README.md
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_file_header.erb
To make a vhost reachable over 2 IP addresses we need to configure 2
similar vhosts which differ in the IP address. This change allows to use an array
of IPs.
Ticket: https://tickets.puppetlabs.com/browse/MODULES-2544
Since Release 0.9.0 we have a dependency on stdlib >= 2.4.x [CHANGELOG](https://github.com/puppetlabs/puppetlabs-apache/blob/master/CHANGELOG.md#backwards-incompatible-changes-1)
With the changes in this pull requests we need stdlib >= 4.0.0 since `suffix()`  is not available in Release 2.4.x [stdlib CHANGELOG](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/CHANGELOG.md#2013-03-26---richard-soderberg-rsoderbergmozillacom---400),  [Code](https://github.com/puppetlabs/puppetlabs-apache/pull/1229/files#diff-c918e8884948c0fae251b33071374150R343)
> #2544 Allow multiple IP addresses per vhost

- README.md
- manifests/params.pp
- spec/classes/apache_spec.rb
For security reasons Debian changes default docroot to /var/www/html. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=730372
> (MODULES-2651) Default document root update for Ubuntu 14.04 and Debian 8

- README.md
- templates/vhost/_file_header.erb
Changing template to wrap ServerName in an if statement so you can set $::apache::vhost::servername to false and skip adding ServerName to the config.
> (MODULES-2757) Adding if around ServerName in template

- manifests/params.pp
- spec/acceptance/mod_mime_spec.rb
Hello, 
The last commit had introduced a new feature about adding dynamic AddHandler/AddType.
There is a little typo error. The "right" syntax should be :
AddType text/html .shtml
Regards
Olivier
> Fix typo about dynamic AddHandler/AddType

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_auth_kerb.erb
Hello, 
According to the http://modauthkerb.sourceforge.net/configure.html webpage,
the 3  following parameters are missing.
- KrbVerifyKDC
- KrbServiceName
- KrbSaveCredentials
Regards
Olivier
> Add missing parameters in mod_auth_kerb

- lib/puppet/parser/functions/enclose_ipv6.rb
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- spec/unit/puppet/parser/functions/enclose_ipv6_spec.rb
The apache module does enclose IPv6 addresses in square brackets as
apache recommends
Apache 2.2:
https://httpd.apache.org/docs/2.2/en/bind.html
https://httpd.apache.org/docs/2.2/en/mod/core.html#virtualhost
https://httpd.apache.org/docs/2.2/en/mod/core.html#namevirtualhost
Apache 2.4:
https://httpd.apache.org/docs/2.4/en/bind.html
https://httpd.apache.org/docs/2.4/en/mod/core.html#virtualhost
Ticket: https://tickets.puppetlabs.com/browse/MODULES-2764
> (MODULES-2764) Enclose IPv6 addresses in square brackets

- manifests/mod/nss.pp
- templates/mod/nss.conf.erb
I added ability to mod_nss to be able to change listen port from default 8443 to for example 443, which is default https(SSL) port. It is quite useful for us.
> Add support for changing mod_nss listen port (vol 2)

- README.md
- README.passenger.md
Fixes several typos and links, reorganizes the
`apache::mod::auth_mellon`, `mellon_enable`,
and `auth_kerb` sections, and documents 
missing default values.
> (docs) Fix issues with the 1.7.0 readme.

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Instead to default require to 'Require all granted' if no 'require'
parameter is set for a directory, leave require unmanaged in apache 2.4
if needed. This is useful for complex authentication/authorization
requirements which are handled in a custom fragment.
> Leave require directive unmanaged

- README.md
- manifests/custom_config.pp
- spec/acceptance/custom_config_spec.rb
We discussed this a couple times in modules triage.  I proposed it in in comments in PR #1201, but haven't seen any response from the pull requester.  I'm putting it up so we can review it separately.
> add ability to overide file name generation in custom_config

- README.md
- manifests/mod/ldap.pp
- spec/classes/mod/ldap_spec.rb
- templates/mod/ldap.conf.erb
This adds the Apache mod LDAP option described here: https://httpd.apache.org/docs/2.2/mod/mod_ldap.html#ldaptrustedglobalcert
Not sure of the best place to document the functionality though?
> Added support for LDAPTrustedGlobalCert option to apache::mod::ldap

- templates/mod/fastcgi.conf.erb
- templates/vhost/_directories.erb
FilesMatch and AddHandler do not interact correctly, which caused the fcgi
tests to (correctly) complain about php-cgi not being started for the fcgi
configuration.
Using FilesMatch in all cases addresses both the original security issue
(better) and leads to correct resolution of handlers again.
> (MODULES-2682, FM-3919) Use more FilesMatch

- spec/acceptance/mod_fcgid_spec.rb
The original line before the refactor in https://github.com/puppetlabs/puppetlabs-apache/pull/1282/files#diff-1eac7b1e1ab2d890671f09f88394db74L4 was a 2 tier conditional. The first is to NOT RUN the `describe` block on `UNSUPPORTED_PLATFORMS` and `OracleLinux 7`. Then the second conditional was to RUN the `context` block if `RedHat != 5`. So effectively, the combination of these conditionals leads to tests only running if on RedHat and version != 5 AND NOT OracleLinux 7
The refactor changed the conditional to:
`:if => ((fact('osfamily') == 'RedHat' and fact('operatingsystemmajrelease') != '5') or (fact('operatingsystem') != 'OracleLinux' and fact('operatingsystemmajrelease') != '7'))`
Due to the latter part after the `or`, the subsequent tests will run on all OS except OracleLinux7.
> (MAINT) Fix conditional flag on mod_fcgid test.

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_ssl.erb
- templates/vhost/_sslproxy.erb
RewriteRules and ProxyPass directives can require SSLProxy*
configurations even if SSLEngine is not enabled.
This PR should be updated with options added in #1268 once
that one is merged.
> (MODULES-2863) Set SSLProxy directives even if ssl is false

- README.md
- manifests/vhost.pp
- manifests/vhost/custom.pp
- spec/defines/vhost_custom_spec.rb
Here we are adding a thin wrapper to apache::custom_config but setting
default specific to the vhost apache folder.
> Add ::apache::vhost::custom

- README.md
- spec/acceptance/vhost_spec.rb
libapache2-mod-fastcgi exists only in multiverse for Ubuntu, so warn
the user they need to enable it.
> Add note about fastcgi usage

- spec/acceptance/vhost_spec.rb
Since we don't have any packaging for it.
> Skip fastcgi acceptance testing for Centos 7

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
Manifest compilation fails when an empty array is passed as rewrites
parameter to vhost defined type.
This commit makes the code to compile nicely.
> fix validation error when empty array is passed as rewrites parameter

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
This simple commmit adds the ability to use a proxy provider for
directories.
http://httpd.apache.org/docs/current/sections.html
My use case is to have a <Proxy "*"> section to apply directives to all
my proxies definitions.
> Support proxy provider for vhost directories.

- manifests/vhost.pp
I have scenario where I need the request headers template to be rendered before the proxy template so I can remove an Authorization header before it goes across the proxy, e.g., 
```
RequestHeader unset Authorization
...
```
When the `RequestHeader unset` directive is after the proxy section, the header is sent to the proxy.
This change allows the order parameter of the request headers template to be changed without affecting current behavior.
> Put headers and request headers before proxy

- manifests/params.pp
- spec/acceptance/apache_ssl_spec.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/default_mods_spec.rb
- spec/acceptance/mod_dav_svn_spec.rb
- spec/acceptance/mod_deflate_spec.rb
- spec/acceptance/mod_mime_spec.rb
- spec/acceptance/mod_negotiation_spec.rb
- spec/acceptance/mod_pagespeed_spec.rb
- spec/acceptance/mod_passenger_spec.rb
- spec/acceptance/mod_php_spec.rb
- spec/acceptance/mod_proxy_html_spec.rb
- spec/acceptance/mod_security_spec.rb
- spec/acceptance/prefork_worker_spec.rb
- spec/acceptance/version.rb
- spec/classes/mod/security_spec.rb
This is briefly mentioned in [MODULES-1734](https://tickets.puppetlabs.com/browse/MODULES-1734), but EL7 uses the conf.modules.d directory for module configuration.
> EL7 uses conf.modules.d directory for modules.

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
Hey,
I've added ProxyPassReverseCookieDomain directive in mod_proxy.
Regards,
Cem
> Support the mod_proxy ProxPassReverseCookieDomain directive  

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_sslproxy.erb
I've added SSLProxyVerify directive in mod ssl.
> SSLProxyVerify

- templates/httpd.conf.erb
In order to log the X-Forwarded-For client ip address or the real
client ip address add LogFormats default directive.
> Add X-Forwarded-For into log_formats defaults

- templates/vhost/_proxy.erb
change iteration over hash elements from 'each_pair' to sorted keys. As the
order of hash elements is not specified, and might be different every run,
sorted keys ensure that the order of ProxyPass and ProxyPassMatch parameters
are the same every time.
> ensure hash order is sorted in template

- manifests/params.pp
This allows the apache::mod::shib2 class to work on Debian hosts.
> Fixes paths and packages for the shib2 module on Debian

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
In order to configure authentication within apache to be a reverse proxy for an authenticated resource authentication methods need to be defined within the Location block.  This allows defining those options (and any others someone may want) within that block.
> MODULES-2956: Enable options within location block on proxy_match

- README.md
Add missed predefined "forwarded" log format into docs.
> Update docs for predefined LogFormats

- templates/vhost/_proxy.erb
this has been fixed for a long time
(https://bz.apache.org/bugzilla/show_bug.cgi?id=38864) and the
workaround documented by @niq http://www.apachetutor.org/admin/reverseproxies
hasn't been necessary for a long time.
> proxy: remove workaround for old broken clients

- lib/puppet/parser/functions/enclose_ipv6.rb
- spec/defines/vhost_spec.rb
- spec/unit/puppet/parser/functions/enclose_ipv6_spec.rb
```
apache::vhost { 'test':
ip => '*',
}
```
currently fails. This PR fixes the behavior.
> fix vhosts listen to wildcard ip

- README.md
- manifests/balancer.pp
- manifests/fastcgi/server.pp
- manifests/init.pp
- manifests/mod.pp
- manifests/mod/event.pp
- manifests/mod/itk.pp
- manifests/mod/peruser.pp
- manifests/mod/php.pp
- manifests/mod/prefork.pp
- manifests/mod/worker.pp
- manifests/params.pp
- manifests/vhost.pp
- manifests/vhost/custom.pp
- spec/classes/apache_spec.rb
- spec/defines/mod_spec.rb
This PR adds an parameter `file_mode` to specify the desired permissions mode the config files are created with.
> add paramter to set config file permissions

- manifests/init.pp
- manifests/params.pp
https://tickets.puppetlabs.com/browse/MODULES-2990
update module handling for gentoo when used apache 2.4
add module authnz_external as external package in gentoo
> MODULES-2990: Gentoo - fix module includes in portage::makeconf

- manifests/mod/passenger.pp
- spec/classes/mod/passenger_spec.rb
mod_passenger provides a passenger.conf containing PassengerRoot to
ensure the service starts up correctly.  On EL7, this is installed at
/etc/httpd/conf.d/passenger.conf and has been protected from purging
since 005bf61.
The change in 2a608592 to move LoadModule config files to
/etc/httpd/conf.modules.d/ on EL7 also affected the path of the
protected passenger.conf.  This change reverts the path change to match
the packages.
In summary, prior to 2a608592 (release 1.7.0):
- /etc/httpd/conf.d/passenger.conf with PassengerRoot (packaged)
- /etc/httpd/conf.d/passenger_extra.conf with apache::mod::passenger settings
- /etc/httpd/conf.d/zpassenger.load with LoadModule
In 2a608592 (release 1.8.0):
- /etc/httpd/conf.modules.d/passenger_extra.conf with apache::mod::passenger settings
- …
> Preserve /etc/httpd/conf.d/passenger.conf on EL7

- manifests/init.pp
- spec/classes/apache_spec.rb
The $ports_file is created via the concat resource, not the file resource.
Therefore, the related require attribute should reference concat, not file.
This also fixes [bug 2850](https://tickets.puppetlabs.com/browse/MODULES-2850)
> Bugfix: require concat, not file

- README.md
- manifests/mod/passenger.pp
- manifests/params.pp
- spec/acceptance/mod_passenger_spec.rb
- spec/acceptance/vhost_spec.rb
Passenger needs their own repository now, so this PR adds that repo to
the apache::mod::passenger class.
It also updates the readme documenting which mods need epel or other
extra repositories (or at least the packages provided by those repos).
It also updates the style of the readme and some other linting issues.
> Fix passenger on redhat systems

- README.md
- manifests/init.pp
- manifests/params.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
This PR adds the parameter root_directory_options to the apache class in order to change the options in httpd.conf:
```
<Directory />
Options FollowSymLinks
AllowOverride None
</Directory>
```
This is necessary for hardening of apache, e.g. it is done in the hardening.io project.
> add parameter root_directory_options

- spec/acceptance/mod_passenger_spec.rb
The module does not yet manage passenger.conf with puppet and so any two
tests that use passenger with non-passenger tests between them will
cause failures.
> Disable passenger tests other than vhost

- lib/facter/apache_version.rb
The custom fact defined by lib/facter/apache_version.rb runs
"apachectl -v" and applies the following regular expression:
```
^Server version: Apache\/([\w\.]+) \(([\w]+)\)
```
On RHEL 7.1, running apachectl -v produces the following output:
```
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
```
The regex fails to match the output because it does not allow
for whitespace inside the parentheses.  The following modified
regex matches properly:
```
^Server version: Apache\/([\w\.]+) \(([\w ]+)\)
```
> Fix in custom fact "apache_version" for RHEL.

- README.md
- spec/acceptance/vhost_spec.rb
RedHat 6 platforms need either their kernel updated (which we can't do
in testing) or selinux disabled and rebooted (which is silly) so lets
just disable the test.
> Disable passenger tests on redhatish 6

- README.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
This allows the end user to explicitly define or override what the `SSLMutex` or `Mutex` configuration for Apache will be as the platform default might not always be desirable.
Supersedes #1346
Closes #1346
> mod/ssl: Add option to configure SSL mutex

- manifests/mod/deflate.pp
This fixes a compile error where the require on Exec["mkdir ${::apache::mod_dir}"] was failing because it couldn't resolve ${::apache::mod_dir}.
> (MODULES-2756) Adding include ::apache so mkdir exec works properly

- spec/acceptance/vhost_spec.rb
The pending calls didn't have blocks before, so the tests continued to
run as usual. They have to be inside a pending block to work correctly
> Move rack test to pending block

- spec/classes/mod/rpaf_spec.rb
- templates/mod/rpaf.conf.erb
mod_rpaf: I changed the names of the different configuration directives as described on https://github.com/gnif/mod_rpaf
modified files:
spec/classes/mod/rpaf_spec.rb
templates/mod/rpaf.conf.erb
os: rhel/centos 6
- httpd-2.2
- mod_rpaf
> changed rpaf Configuration Directives: RPAF -> RPAF_

- manifests/mod.pp
The problem I'm running into on EL7 is that when the ssl module is enabled, the mod_ssl package gets installed and drops `/etc/httpd/conf.d/ssl.conf`. We want to remove that file, but the purge for `/etc/httpd/conf.d` is being evaluated before the mod_ssl package is being installed. Because both ports.conf and ssl.conf have Listen statements for port 443, apache won't start. On the second client run the `ssl.conf` file will be removed and apache starts fine.
This change ensures that the `mod_ssl` package gets installed prior to the purge on `/etc/httpd/conf.d` being evaluated so that the ssl.conf file gets removed on the first client run.
> Ensure module packages are installed before evaluating conf.d dir

- examples/vhost.pp
There is no HTTPS_HOST variable in mod_rewrite
> [MODULES-1628] Fix mod rewrite typo in examples

- README.md
The README describes the shib_request_settings param under the `shib_request_setting` heading. This commit fixes the heading to match the param name, thus reducing confusion.
> Fix typo in README for shib_request_settings vhost param

- README.md
- manifests/fastcgi/server.pp
- spec/defines/fastcgi_server_spec.rb
- templates/fastcgi/server.erb
For local fcgi servers it makes sense to skip the TCP stack and communicate via socket.
This is also sugested in #MODULES-1405.
Instead of introducing a new parameter socket, validate functions are used to decide if we have a host or a socket in parameter `host`. 
It might be confusing to pass a socket path to a parameter named `host`, but changing the host parameter name to something like `host_or_socket` would introduce backwards incompatibility.
> Support socket communication option in apache::fastcgi::server

- manifests/balancer.pp
- manifests/balancermember.pp
- spec/defines/balancer_spec.rb
- spec/defines/balancermember_spec.rb
Thit commits implements a target parameter to the apache::balancer
definition to specify a different configuration path if needed (e.g with
a different suffix or in a different location).
> apache::balancer: Add a target parameter to write to a custom path

- manifests/init.pp
On Ubuntu Trusty, the default mpm module is "event". In
puppetlabs-apache, the default mpm module is "worker". These can't both
be loaded at once. The apache puppet module takes care of this by
purging the mods-enabled directory. However, if we try to run a syntax
check before the directory is purged, it fails. The
apache::custom_config defined type contains an "syntax verification for
${name}" exec that can potentially run before the event mod is unloaded.
This patch ensures that the module purging occurs before syntax check
happens so that the puppet run is successful.
> Manage mod dir before things that depend on mods

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_jk_mounts.erb
`mod_jk` is one of the possibilities to use Apache as a frontend to Tomcat. The module understands `JkMount` and `JkUnMount` directives to configure whether an URL should be handled by Apache or by Tomcat. This patch enhances `apache::vhost` to allow configuration of these two directives for a virtual host.
> Add JkMount/JkUnmount directives to vhost

- README.md
- manifests/mod/security.pp
- manifests/params.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
The default configuration for this includes "I" which is not always
always suitable, e.g. if you cannot tolerate POST parameters appearing
in your modsec_audit.log
You may want to omit `I` if mod_security is protecting a hypothetical
web service that accepts credit card data in a POST request, for
example.
> Allow configuring mod_security's SecAuditLogParts

- spec/acceptance/vhost_spec.rb
multiverse is needed for libapache2-mod-fastcgi but is not enabled by
default on any Ubuntu release.
> Enable multiverse on all Ubuntu hosts

- manifests/mod/authnz_ldap.pp
- spec/classes/mod/authnz_ldap_spec.rb
- templates/mod/authnz_ldap.conf.erb
According to this document, uppercase letters are not allowed:
https://docs.puppetlabs.com/puppet/latest/reference/lang_reserved.html#parameters
> Use valid parameter name

- manifests/balancer.pp
- manifests/balancermember.pp
- manifests/init.pp
- manifests/listen.pp
- manifests/namevirtualhost.pp
Deprecated in 1.1.x and has no effect in 2.x.  From commit 1919eb3, but
was reverted when temporarily removing 2.x support in f54393e.
> Move all ensure parameters from concat::fragment to concat

- README.md
- manifests/mod/ssl.pp
- templates/mod/ssl.conf.erb
1. Fix MODULES-3158 (any string interpreted as SSLCompression on)
1. Convert ssl_honorcipherorder to boolean, backport accepting 'on' or 'off'
> Fix MODULES-3158 (any string interpreted as SSLCompression on)

- templates/mod/ssl.conf.erb
In #1398 @igalic suggests replacing 2 sections of the SSL configuration Ruby template with a function designed to safely convert Booleans to their Apache On/Off equivalent. This PR implements the suggestion.
The PR should be safe because #1398 modifies the Puppet code to ensure that each variable is already a boolean with the intended default value.
> Take igalic's suggestion to use bool2httpd

- templates/mod/ssl.conf.erb
Commit: 3ccd3294dcd866bdc1cf3a3901bcc0b5d21a7c25 brokes apache 2.2 config.
http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcompression
> SSLCompression directive only available with apache 2.4.3

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_sslproxy.erb
Adding SSLProxyCheckPeerExpire support, and fixes a couple of copy/paste errors in the readme related to the SSL Proxy directives.
> Adding SSLProxyCheckPeerExpire support

- README.md
- manifests/mod/passenger.pp
- spec/classes/mod/passenger_spec.rb
- templates/mod/passenger.conf.erb
I added a parameter passenger_log_level to be able to configure the PassengerLogLevel option in passenger.conf.
> Add parameter passanger_log_level

- lib/facter/apache_version.rb
- spec/unit/apache_version_spec.rb
The custom fact defined by lib/facter/apache_version.rb runs
"apachectl -v" and applies the following regular expression:
^Server version: Apache\/([\w\.]+) \(([\w ]+)\)
On OracleLinux 7.2, running apachectl -v produces the following output:
Server version: Apache/2.4.6 ()
Server built:   Nov 21 2015 05:34:59
The regex fails to match the output because it does not allow
nothing inside the parentheses.  The following modified
regex matches properly:
^Server version: Apache\/([\w\.]+) \(([\w ]*)\)
> Fix in custom fact "apache_version" for OracleLinux.

- manifests/mod.pp
- manifests/mod/pagespeed.pp
Google recommends that we always stay on the latest version of mod-pagespeed-stable, which is what is installed with this module. I added changes here to allow for having the latest version of mod-pagespeed-stable.
> Allow for pagespeed mod to automatically be updated to the latest version

- templates/mod/pagespeed.conf.erb
Assuming a puppet file with the following from `::apache::mod::pagespeed`
```
additional_configuration      => [
"ModPagespeedEnableCachePurge $mod_pagespeed_enable_cache_purge",
"ModPagespeedAnalyticsID $analytics_id",
'ModPagespeedDisallow */APOS/*',
'ModPagespeedDisallow */jasperserver-pro/*',
],  
```
this is evaluated:
```
<% if @additional_configuration.is_a? Array -%>
<%= @additional_configuration.join('\n') %>
<% else -%>
```
resulting in this...
```
ModPagespeedEnableCachePurge On\nModPagespeedAnalyticsID UA-xxxx-1\nModPagespeedDisallow */APOS/*\nModPagespeedDisallow */jasperserver-pro/*
```
Using double quotes for the .join("\n") makes it work correctly:
```
ModPagespeedEnableCachePurge On
ModPagespeedAnalyticsID UA-xxxx-1
ModPagespeedDisallow */APOS/*
ModPagespeedDisallow …
```
> fix incorrect use of .join() with newlines

- manifests/mod/proxy_fcgi.pp
This adds simple support for enabling the fcgi module.
> add support for fcgi

- README.md
- manifests/vhost.pp
- spec/acceptance/mod_security_spec.rb
- templates/vhost/_security.erb
- documentation included
- tests included
- all tests successfully passed (rake spec, rspec spec/acceptance)
> Added vhost options SecRuleRemoveByTag and SecRuleRemoveByMsg

- README.md
- manifests/mod/authnz_ldap.pp
- manifests/mod/ldap.pp
- manifests/mod/proxy.pp
Simple change to allow users to change the package name on the aforementioned mods. This is based on the code for mod::ssl, which already had this feature.
I'm not (very) experienced in the subject of spec tests and could use some help if those need to be improved as well. The code works as expected in my setup.
> Allow package names to be specified for mod_proxy, mod_ldap, and mod_authnz_ldap

- README.md
- manifests/vhost/custom.pp
In many cases verify_config confuses more than it helps and users would
like to be able to turn it off. Expose the
$apache::custom_config::verify_config parameter in
apache::vhost::custom so custom vhost users can also turn this off.
> Expose verify_config in apache::vhost::custom

- spec/acceptance/default_mods_spec.rb
Debian 7 and Ubuntu 12.04's init scripts will refuse to restart the service
if the configuration is broken. So this commit adds an explicit
configuration step to shutdown the apache before the test.
> (maint) update apache::default_mods tests to work on debian 7

- README.md
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
- templates/vhost/_proxy.erb
- templates/vhost/_require.erb
The main commit in this PR introduces minimal support for the \<Limit\> block inside \<Location\> blocks.
To do this, the template code handling "Require" directives has been refactored to a template of its own to avoid code duplication. This new template in turn then gets included in the main _directories.erb template, both directly inside the \<Location\> block and also inside each \<Limit\> block.
Additionally, this PR also includes the relatively straightforward support for the ProxyAddHeaders directive.
> Add simple <Limit> support + ProxyAddHeaders

- manifests/params.pp
Because of the trailing slash in `$lib_path` the following code (in manifests/mod.pp) produces output with two slashes on Suse Systems:
```
} else {
$_path = "${lib_path}/${_lib}"
}
```
> Fixed trailing slash in lib_path on Suse

- spec/classes/mod/rpaf_spec.rb
- templates/mod/rpaf.conf.erb
This reverts commit 8ca7a6697ab907803789b2aa63e304f19e3497d3.
These changes are completely incompatible with mod_rpaf as provided in
Ubuntu 12.04 and Debian Jessie and Wheezy, and break the Apache
configuration and consequently the Puppet agent run.
I suspect these changes were made to be compatible with one of the
mod_rpaf forks (https://github.com/gnif/mod_rpaf) but I don't see how a
"random" fork should have precedence over, and break modules distributed
on the official channels.
> Revert "changed rpaf Configuration Directives: RPAF -> RPAF_"

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
Revert "MODULES-2956: Enable options within location block on proxy_match"
this commit removes the location directive in _proxy.erb
proxy: remove workaround for old broken clients
99add117df452d2c513a3a7c36d9fd0416e696b9
this commit sets options in the location directive in _proxy.erb
MODULES-2956: Enable options within location block on proxy_match
db5b0bfb09959622ea1c6cc299b58057b94c588f
setting options-hash in proxy_pass or proxy_match now leads to syntax errors
in Apache like "AuthBasicProvider not allowed here"
> setting options-hash in proxy_pass or proxy_match leads to syntax errors in Apache

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_keepalive_options.erb
Introduce the parameters vhost::keepalive, vhost::keepalive_timeout and
vhost::max_keepalive_requests, which are all undef by default, meaning
the server-wide KeepAlive options will be in effect. This way the
KeepAlive settings can be changed on a per-vhost basis.
Includes updated documentation and basic spec tests.
> Allow setting KeepAlive related options per vhost

- manifests/params.pp
This unbreaks snippets verification.
> Set actual path to apachectl on FreeBSD.

- README.md
- manifests/mod/event.pp
- spec/classes/mod/event_spec.rb
- templates/mod/event.conf.erb
The Name of the Parameters MaxRequestWorkers and MaxConnectionsPerChild  for mod_event changed between versions as the README already shows (mixed up though).
The apache module should not set both the old and the new parameter name, but instead just one of them.
The old names are still supported so it's better (and safe) to set the old names than both.
See:
* https://httpd.apache.org/docs/current/en/mod/mpm_common.html#maxconnectionsperchild
* https://httpd.apache.org/docs/current/en/mod/mpm_common.html#maxrequestworkers
> mod_event: do not set parameters twice

- spec/acceptance/mod_pagespeed_spec.rb
Because libc6 package on Debian Wheezy repo is old, and Pagespeed needs newer.
> (maint) Disables mod_pagespeed tests for Debian 7

- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
The default for SSLCompression in Apache is 'Off' anyways, see:
https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslcompression
therefore there is no real need to add that into the config file.
This will prevent problems on Apache versions that have
linked against SSL libraries that do not have SSLCompression
enabled. There, even SSLCompression Off will lead to:
H00526: Syntax error on line 14 of /etc/apache2/modules/ssl.conf:
Setting Compression mode unsupported; not implemented by the SSL library
and prevents Apache startup
Add some spec tests for that behaviour, depending on whether Apache
version >= 2.4 or not, since the template also differentiates.
> Only set SSLCompression when it is set to true.

- README.md
- spec/classes/mod/event_spec.rb
- templates/mod/event.conf.erb
The commit adds the ability to unset mod_event parameters. This is useful if you want to use apache defaults.
> mod_event: parameters can be unset

- README.md
- manifests/vhosts.pp
- spec/acceptance/vhosts_spec.rb
- spec/classes/vhosts_spec.rb
This way it is possible to create apache::vhost resources directly via the main class without declaring them in a separate role or profile.
> Add class apache::vhosts to create apache::vhost resources

- manifests/params.pp
Prevents warning under Puppet 4:
The key 'shib2' is declared more than once at modules/apache/manifests/params.pp:241:21
> Remove duplicate shib2 hash element

- manifests/init.pp
Change the use of an empty class declaration to an include statement.
This enables the relevant mpm_module to be safely declared elsewhere with custom parameters.
> (MODULES-3388) Include mpm_module classes instead of class declaration

- manifests/balancer.pp
- spec/defines/balancer_spec.rb
Previously with a configuration of
```
class{'apache':
confd_dir => '/my/directory':
}
balancer{'myb':}
```
balencer would create a file incorrectly in the default location
*/etc/apache2/conf.d/balancer_myb.conf*
balencer now uses the value *apache::confd_dir*.
A test case has been added for this bug.
> apache::balancer now respects apache::confd_dir

- manifests/mod/itk.pp
on apache >= 2.4
include apache::mod::prefork in manifests/mod/itk.pp instead.
because cant include apache::mod::prefork before class apache:
"Warning: Scope(Class[Apache::Mod::Prefork]): Could not look up qualified variable '::apache::apache_version'; class ::apache has not been evaluated" results in 
"Error: Could not find dependency Exec[mkdir ] for File[/prefork.conf] at apache/manifests/mod/prefork.pp:44"
> dont fail if mpm_module is itk and class apache::mod::prefork is not defined

- README.md
When using the new Apache 2.4 Require(Any|All|None) syntax in puppet the hash value for this is named requires in the code and not require. Further more the array with require examples was not really easy readable.
> fix and make 2.4 require docu more readable

- README.md
- manifests/init.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
Currently the root directory setting in httpd.conf provides an open access policy. By default Apache has access to all directories on the host. In some cases it may be desirable to deny access by default and explicitly configure access rights to every resource.
This patch adds the boolean `root_directory_secured` parameter to the main class. Setting this parameter to `true` will add a `Deny from all` (Apache 2.2) or a `Require all denied` (Apache 2.4) directive to the Apache config for the root directory. Setting the parameter to `false` will leave out these directives. The parameter default is `false` to remain backwards compatible.
> Manage default root directory access rights

- manifests/mod.pp
It's now possible to use the default_mods parameter in combination with apache_version 2.4 on an Amazon Linux system
> Added support for apache 2.4 on Amazon Linux

- README.md
- templates/vhost/_directories.erb
* AuthLDAPURL as auth_ldap_url
* AUTHLDAPBindDN as auth_ldap_bind_dn
* AuthLDAPBindPassword as auth_ldap_bind_password
> add additional directories options for LDAP Auth

- templates/mod/remoteip.conf.erb
Hi,
There is a non breaking space in the file templates/mod/remoteip.conf.erb :
```
jeo@brs:~/dev/tmp/puppetlabs-apache/templates/mod$ cat -A remoteip.conf.erb 
..
#M-BM- the RemoteIPHeader value$
..
```
This breaks Puppet runs : 
```
root@monserver /data/sites/web-all-share-01/htdocs/data # puppet agent -t --no-noop
Info: Using configured environment 'master'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for myserver
Info: Applying configuration version '1466490720'
Error: invalid byte sequence in US-ASCII
Error: /Stage[main]/Apache::Mod::Remoteip/File[remoteip.conf]/content: change from {md5}0751dee096af1710db45615e82ccc979 to {md5}7db1e4a128ab3879d330416c6972e033 failed: invalid byte sequence in US-ASCII
```
> Fix non breaking space (MODULES-3503)

- manifests/mod/socache_shmcb.pp
- manifests/mod/ssl.pp
I am not sure if this is the best way to address this: I already got `::apache::mod { 'socache_shmcb': }` in my Apache profile classes because I need it to support database-backed authentication.
Now I would like to include `apache::mod::ssl` as well which in turn also declares `::apache::mod { 'socache_shmcb': }`.
If there is a better (more "Puppet" way) of solving this, please let me know. Otherwise, I hope that this PR allows to simply `include apache::mod::socache_shmcb` and be set.
> Add apache::mod::socache_shmcb so it can be included multiple times

- README.md
- manifests/mod/dumpio.pp
- spec/classes/mod/dumpio_spec.rb
- templates/mod/dumpio.conf.erb
New module class for dumpio with parameters for enabling input and/or
output dumping.
```puppet
class{'apache':
default_mods => false,
log_level    => 'dumpio:trace7',
}
class{'apache::mod::diskio':
disk_io_input  => 'On',
disk_io_output => 'Off',
}
```
* https://httpd.apache.org/docs/2.4/mod/mod_dumpio.html
> mod_dumpio configuration

- README.md
- manifests/mod/auth_cas.pp
- templates/mod/auth_cas.conf.erb
We need this to open up write to all in the apache group.
> Add cas_cookie_path_mode param

- README.md
- manifests/mod/security.pp
- manifests/security/rule_link.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
- templates/mod/security_crs.conf.erb
This combines and replaces  #1486,  #1487, and  #1491. 
This also supersedes #1474.
> Combined PR for Sec changes

- templates/vhost/_auth_cas.erb
The CAS directives are explicit (they start with CAS), and the comment was seen even without any CAS option set
> Remove CAS comment

- manifests/init.pp
We've encountered an issue with Puppet trying to purge the confdir. We organise our Apache config in a conf.d style manner. When Puppet is instructed to purge a directory which contains directories it will complain that you must set the force parameter to really delete directories (see https://docs.puppet.com/puppet/3.8/reference/type.html#file-attribute-purge).
We think that purging the confdir should also include directories that may be present.
What do you think about this?
```
Notice: /Stage[main]/Apache/File[/etc/httpd/conf.d/test.d]: Not removing directory; use 'force' to override
```
> add force option to confd file resource

- spec/acceptance/vhost_spec.rb
- templates/vhost/_file_header.erb
If an empty servername is given to a vhost, it shouldn't be written
to the configuration file. Else we'll end up with an invalid
configuration and httpd will fail to start. It is actually valid not
to have a Servername, and in this case, httpd will route only based
on the IP.
This resolves bug https://tickets.puppetlabs.com/browse/MODULES-3882
> [MODULES-3882] Don't write empty servername for vhost to template

- README.md
- manifests/package.pp
Hi,
The FreeBSD `www/apache24` package is now friendlier at switching MPM :cake: 
This remove a lot of code from `manifests/package.pp`, and I wonder if it would not be even better to get rid of the switch / case too.  If so, please tell me and I'll add a commit on top of this.
Thanks !
> Simplify MPM setup on FreeBSD

- README.md
- manifests/mod/authn_dbd.pp
- manifests/mod/dbd.pp
- spec/classes/mod/authn_dbd_spec.rb
- templates/mod/authn_dbd.conf.erb
There was previously no facility to configure dbd for use with
authn_dbd.  I want to keep the apache config I required within the scope
of this module.
> MODULES-3682 - config of auth_dbd, include dbd, allow AuthnProviderAlias

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_passenger.erb
For passenger NodeJS Apps we need some more params
- passenger_nodejs (https://www.phusionpassenger.com/library/config/apache/reference/#passengernodejs) - Available with 4.0.24
- passenger_sticky_sessions (https://www.phusionpassenger.com/library/config/apache/reference/#passengerstickysessions) - Available with 4.0.45
- passenger_startup_file (https://www.phusionpassenger.com/library/config/apache/reference/#passengerstartupfile) - Passenger has a good default, but for Express app generator we must set this param. Available with 4.0.25
If you need anything, let me know
Greetings Reamer
> Add some more passenger params

- templates/mod/security.conf.erb
By moving the Include statements to the bottom of the configuration file rules 200001, 200002, and 200003 defined in modsecurity.conf can be disabled/modified in included files such as `/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_60_customrules.conf`.
In the current configuration the Includes are evaluated first which means the rule set is ordered as such:
```
SecRuleRemoveById 200003
SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" \
"id:'200003',phase:2,t:none,log,deny,status:44,msg:'Multipart parser detected a possible unmatched boundary.'"
```
Unfortunately when ordered like this, the rule is enforced.
Fedora 24 has moved the Include statements at the bottom of the configuration file. The other option would be to add parameters to `apache::mod::security` to disable these …
> move IncludeOptional to bottom of configuration

- manifests/mod/shib.pp
Shibboleth can be installed in very different location using different
names depending on the version, os... We add a parameter to specify the
location of the current shibboleth library path.
> Add path to shibboleth lib

- manifests/vhost/custom.pp
The notify was present in the regular vhost.pp manifest, but not in the
vhost/custom.pp manifest
> Notify Apache of new symlink

- README.md
- manifests/params.pp
The previously configured directory (apache configuration directory) does NOT contain certificates by default, resulting in an error when starting apache if certificates are elsewhere (i.e. a VirtualHost with constomized vertificate and key):
~~~
[Tue Oct 18 16:34:17.074516 2016] [ssl:emerg] [pid 57102:tid 34397585408] AH01896: Unable to determine list of acceptable CA certificates for client authentication
~~~
While here, sync the README which was outdated.
> Do not set ssl_certs_dir on FreeBSD

- manifests/mod/shib.pp
If left `undef`, they remain the values set in `params.pp`. The context is that more up-to-date packages are typically available from external repositories such as from [Switch](https://www.switch.ch/aai/guides/sp/installation/) but they use different package names (that force the OS packages to uninstall) and potentially different library files. These parameters allow a generic way to override the defaults without affecting existing configurations. I have tried to mimic the parameter names used in other modules under `manifests/mod/*` for consistency.
> Allow user to specify alternative package and library names for shibboleth module

- manifests/vhost.pp
An empty string is false on Puppet 3, so this line was causing a failure on acceptance tests on 3.8. '' should be allowed for $servername per https://github.com/puppetlabs/puppetlabs-apache/pull/1526
> (maint) adds to conditional to allow for empty servername

- manifests/init.pp
- manifests/mod/ssl.pp
- manifests/params.pp
This is solving a problem with the SSL configuration on a Red Hat-based
OS that results in a duplicate 'Listen 443' statement after a package
update, causing Apache to no longer start.
The mod_ssl packaging ships a default ssl.conf in apache's main conf
dir, that among other things, contains 'Listen 443'.
However, this module puts all the Listen statements in ports.conf
centralized.
Generally this is no problem, because the module would purge the conf
directory.  Apache hums along happily -- until the apache package gets
an update and it restores the default ssl.conf into
/etc/httpd/conf.d/ssl.conf as no such file exists by the name on EL7
(the module's ssl.conf goes into conf.modules.d).
Apache will then fail to start with this error until puppet runs again:
```
Address already in use: …
```
> Move ssl.conf to main conf directory on EL7

- lib/facter/apache_version.rb
Change the `puts` output to `Facter.debug` so that our structured facts remain side-effect free in normal runs, and can just be piped into tools like `jq`
> custom facts shouldn't break structured facts

- examples/vhost.pp
- examples/vhost_proxypass.pp
- manifests/custom_config.pp
- manifests/init.pp
- manifests/mod/cgi.pp
- manifests/mod/cgid.pp
- manifests/mod/deflate.pp
- manifests/mod/info.pp
- manifests/mod/ssl.pp
- manifests/mpm.pp
- manifests/params.pp
- manifests/vhost.pp
As per style guide v2.0, there must be trailing commas after all
resource attributes and parameter definitions.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Add missing trailing commas

- examples/apache.pp
- examples/dev.pp
- examples/init.pp
- examples/mod_load_params.pp
- examples/mods.pp
- examples/mods_custom.pp
- examples/php.pp
- examples/vhost.pp
- examples/vhost_directories.pp
- examples/vhost_filter.pp
- examples/vhost_ip_based.pp
- examples/vhost_proxypass.pp
- examples/vhost_ssl.pp
- examples/vhosts_without_listen.pp
- manifests/fastcgi/server.pp
Including a class by a relative name might lead to unexpected results;
in addition to that there is also a small performance penalty.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Avoid relative classname inclusion

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
Previously, proxy_pass and proxy_pass_match configuration blocks did not
support using no_proxy_uris and no_proxy_uris_match. These parameters
required the use of proxy_dest, but mixing proxy_pass and proxy_dest
results in undesired duplication of ProxyPass config lines.
Fix by allowing no_proxy_uris and no_proxy_uris_match to be used within
proxy_pass and proxy_pass_match configuration blocks.
This PR is similar to #1521 but addresses the problem better in my opinion.
> Allow no_proxy_uris to be used within proxy_pass

- README.md
- manifests/mod/security.pp
- templates/mod/security.conf.erb
- templates/mod/security_crs.conf.erb
We use an implementation of CAS SSO and  recently we had  problems with modsecurity request size blocking. So, we had made some changes, creating parameters to control request body size and arguments.
> Settings to control modcluster request size

- manifests/vhost.pp
Same as with wsgi_pass_authorization, it only accepts on and off as
values (ignoring the case). So this introduces a similar validation
for wsgi_chunked_request.
> Validate wsgi_chunked_request parameter for vhost

- manifests/vhost.pp
- metadata.json
The template is using [@rewrites].flatten.compact which maps to Puppet's delete_undef_values(flatten([]))
> Don't fail if first element of  is not an hash before flattening

- README.md
- manifests/mod/ssl.pp
- manifests/vhost.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
- templates/vhost/_ssl.erb
It is possible to set a global default stapling on/off
Per vhost this can be overridden.
Based on initial pull request https://github.com/puppetlabs/puppetlabs-apache/pull/907 by David Teirney <david.teirney@orionhealth.com>
> Add SSL stapling

- manifests/mod/security.pp
Class apache::mod::security created 2 files with conflicting configs:
/etc/httpd/modsecurity.d/modsecurity_crs_10_config.conf
/etc/httpd/modsecurity.d/security_crs.conf
File[$modsec_dir] purges this directory and creates latter file
but Package[$crs_package] creates former file in the same directory
This change makes the package be managed before the directory,
so the former file is guaranteed to be purged
> (#MODULES-3744) Process $crs_package before $modsec_dir

- README.md
- manifests/mod/security.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
Pass logroot paramter through to mod security.  
Allows log directory to be configured for custom installs.
> ModSec debug logs to use apache logroot parameter

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_rewrite.erb
Apache module rewrite allows virtual hosts to inherit global rules
if their conf files contain the directive "**RewriteOptions Inherit**"
among rewrite rules
This change includes this directive depending on a boolean parameter
in `apache::vhost` class - **rewrite_inherit** - which defaults to false
> (MODULES-4213) Allow global rewrite rules inheritance in vhosts

- README.md
The class `apache::mod::rewrite` is only documented in README as a note in the `rewrites` option for Virtualhosts. My changes make it more visible in place with the rest of mods.
Did it because took me an hour of in-depth lecture of README to find that.
> Document mod_rewrite with the rest of modules

- manifests/mod/userdir.pp
- templates/mod/userdir.conf.erb
#4516 Add param for AllowOverride values in userdir template
Add a param to the apache::mod::userdir class to accept an array of override value. Replace the hardcoded list in the userdir.conf.erb template with an array join, similar to the existing Options line. Use the previously hardcoded values as the default for the overrides param.
The AllowOverride directive values were previously hardcoded in the template.
https://tickets.puppetlabs.com/browse/MODULES-4516
> Add param for AllowOverride in the userdir.conf template

- README.md
- manifests/mod/cluster.pp
- templates/mod/cluster.conf.erb
If calling class defines `advertise_frequency`, and `server_advertise` is `true`, this change adds the directive `AdvertiseFrequency` in mod_cluster virtual host conf file template
> Modules-4500 Add optional "AdvertiseFrequency" directive in cluster.conf template

- README.md
I omitted the documentation in my previous pull request (#1581).
> Add documentation for FileETag

- README.md
- manifests/mod/ssl.pp
- manifests/params.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
Here is the PR related to [MODULES-4737](https://tickets.puppetlabs.com/browse/MODULES-4737)
- ssl_sessioncache which defaults to OS specific value in params.pp
- ssl_proxy_protocol which defaults to an empty array which means using
Apache defaults (see [Apache doc]( https://httpd.apache.org/docs/current/en/mod/mod_ssl.html#sslproxyprotocol) for more details)
> MODULES-4737 - Additional class params for mod ssl

- README.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
Instead of having to specify a CA file for each vhost, it's possible to
just specify it globally.
> Enable configuring CA file in ssl.conf

- spec/acceptance/vhost_spec.rb
include_src is no longer a parameter in apt::source, which is used in vhost_spec as part of the fastcgi test. Instead, include is now a hash with keys 'deb' and 'src'. 'src' defaults to false as of apt 4.0.0 so I removed include_src altogether with no replacement
> (MODULES-4819) remove include_src parameter from vhost_spec

- README.md
- manifests/params.pp
- spec/acceptance/apache_parameters_spec.rb
According to docs "In some cases this has been shown to result in an almost 50% speedup in latency times for HTML documents with many images."
Ref: http://httpd.apache.org/docs/2.4/mod/core.html#keepalive
> Set default keepalive to On

- templates/mod/cluster.conf.erb
Corrects bad syntax included in [PR #1601](https://github.com/puppetlabs/puppetlabs-apache/pull/1601)
> MODULES-4882 - Include missing "@" in template mod/cluster.conf.erb

- manifests/mod/ssl.pp
https://sweet32.info/
The Sweet32 attack exploits DES or 3DES. 3DES is currently part of the "HIGH" cipher suite. This cipher suite is a default setting in the apache::mod::ssl , leaving any server using the default settings vulnerable. 
Fix: 
Change https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/mod/ssl.pp#L7
Currently: 'HIGH:MEDIUM:!aNULL:!MD5:!RC4'
Should be: 'HIGH:MEDIUM:!aNULL:!MD5:!RC4:!3DES'
Note: Per https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslciphersuite, DES (single DES) is not part of HIGH or MEDIUM, therefor is not enabled with the default settings from the module.
> Explicitly disabled 3DES due to Sweet32 attack.

- manifests/init.pp
- manifests/mod/ssl.pp
- manifests/params.pp
- spec/classes/mod/ssl_spec.rb
ssl.conf location must be maintained to avoid duplicate ssl.confs being
created in both mod_dir and confd_dir on rhel7 package updates, and must
also be based on the parameter values passed into the base apache class
for custom directories.
Closes #1635
> (MODULES-5121) Allow ssl.conf to have better defaults

- manifests/vhost.pp
It might sometimes be desirable to have access and error logs in different folders. This isn't possible at the moment as the `access_log_file`/`error_log_file` is treated as a path relative to `logbase`. This pull request changes the behaviour so that if absolute path is detected, `logbase` is not prepended.
> When absolute path is specified for access_log_file/error_log_file, don't prepend logbase

- manifests/mod/security.pp
mod/security.pp is the only module that ensures the package is `latest`. This change makes the behavior of `mod/security.pp` consistent.
Other modules ensure `present` or `installed`
- mod.pp = present
- mod/php.pp = present
- mod/mime.php = installed
> ensure csr_package is 'installed' instead of 'latest'

- README.md
- manifests/vhost.pp
- templates/vhost/_sslproxy.erb
The SSLProxyVerifyDepth and SSLProxyCACertificateFile directives are missing and should be added to the vhost/_sslproxy.erb template.
https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslproxyverifydepth
https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslproxycacertificatefile
https://tickets.puppetlabs.com/browse/MODULES-4391
> MODULES-4391 add SSLProxyVerifyDepth and SSLProxyCACertificateFile directives

- README.md
- manifests/mod/security.pp
- spec/classes/mod/security_spec.rb
- New param `$deploy_security_crs` set to true by default so the default
behaviour is unchanged.
- new rspec example so that the parameter is spec-tested
> MODULES-4816 - new param for mod::security class

- README.md
parameters loadfile_name, ssl_stapling, and ssl_stapling_return_errors are all valid parameters but none of them are in the apache class as is claimed in the README. this commit removes them.
> (MODULES-4404) remove params from apache class doc

- manifests/params.pp
I checked SLES11 and SLES12 (and openSUSE 42.2) and the group for apache is "www" instead of "wwwrun" on all SUSE systems.
The user is wwwrun and the group www
`$ id wwwrun`
`uid=30(wwwrun) gid=8(www) groups=8(www)`
> fixed apache group for SUSE/SLES Systems (checked for SLES11/12)

- manifests/custom_config.pp
- manifests/init.pp
- manifests/mod/auth_cas.pp
- manifests/mod/authnz_ldap.pp
- manifests/mod/dir.pp
- manifests/mod/dumpio.pp
- manifests/mod/ext_filter.pp
- manifests/mod/ldap.pp
- manifests/mod/passenger.pp
- manifests/mod/php.pp
- manifests/mod/proxy_balancer.pp
- manifests/mod/ssl.pp
- manifests/mod/status.pp
- manifests/service.pp
- manifests/vhost.pp
- metadata.json
- spec/classes/apache_spec.rb
- spec/classes/mod/passenger_spec.rb
- spec/classes/service_spec.rb
- spec/defines/custom_config_spec.rb
goal of this is to get rid of all the legacy valida_* function calls, and not to provide perfect datatypes for all parameters.
> Migrate to puppet4 datatypes

- manifests/mod/authnz_ldap.pp
- templates/mod/authnz_ldap.conf.erb
the $verifyServerCert parameter in the authnz_ldap module class is
deprecated and this removes it and updates the template for the upcoming major release.
> (MODULES-4445) remove deprecated parameter in authnz_ldap

- manifests/mod/cgi.pp
`mod_cgi` is used on other MPM implementations than just `prefork`,
so we have to enforce resource ordering against these too.
> [apache::mod::cgi] Fix: ordering constraint for mod_cgi

- templates/vhost/_wsgi.erb
Hi,
Recently, I found out that the wsgi_script_aliases parameter only supports string type of the value.
I only want to set the **process-group** with a **WSGIScriptAlias** in the HTTPD conf. as below 
```
WSGIScriptAlias / /usr/local/djangoweb/wsgi.py process-group=djangoweb-admin
```
To accomplish this, I create the DSL code like this and the Puppet applies it without any error 
```
::apache::vhost { $title :
ip                          => $listen_ip,
port                        => $port,
servername                  => $server_name,
serveraliases               => $server_aliases,
serveradmin                 => $server_admin,
docroot                     => $doc_root,
wsgi_daemon_process         => $wsgi_daemonprocess_name,
wsgi_daemon_process_options => $_wsgidaemonprocess_opts, …
```
> the wsgi_script_aliases need to support array type of value

- manifests/vhost.pp
Proxying can be enabled when the [P] flag is given to a RewriteRule, not only when ProxyPass is used. In that instance, we may want to be able to set ProxyPreserveHost.
> Ensure that ProxyPreserveHost is set even when ProxyPass (etc) are not.

- manifests/mod/userdir.pp
- spec/classes/mod/userdir_spec.rb
- templates/mod/userdir.conf.erb
> (MODULES-4933) Allow custom UserDir string

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_passenger.erb
Signed-off-by: Pavel Pulec kayn@inuits.eu
> add passenger_max_requests option per vhost

- manifests/params.pp
In Ubuntu Xenial, proxy_html module is include in apache standard
packages, so don't try to install it
> Don't install proxy_html package in ubuntu xenial

- README.md
- manifests/init.pp
- manifests/mod.pp
- manifests/mod/php.pp
- spec/classes/apache_spec.rb
- spec/classes/mod/auth_kerb_spec.rb
When using the SCL packages on CentOS, package names have a prefix that needs to be overridden. With most other attributes in params.pp, this is possible by overriding variables passed to `Class['::apache']`, but in the case of `mod_packages` it's read directly from the params file on use. This is workaroundable by not using the `apache::mod::...` subclasses can calling `apache::mod { 'mod_name' }` directly, but there is a compounding problem.
The `apache::vhost::auth_kerb` parameter is used for for both including the `auth_kerb` modules (using class syntax rather than include, so cannot be duplicated), and for including config snippets in the generated vhost. It's not possible to make use of the config snippet whilst also needing to amend the package name.
This commit follows the …
> MODULES-3838 Pass mod_packages through init.pp to allow overrides

- README.md
- lib/puppet/parser/functions/apache_pw_hash.rb
- spec/unit/puppet/parser/functions/apache_pw_hash_spec.rb
This commit adds a new parser function apache_pw_hash, which
allows generating password hashes to be used in htpasswd files.
> add parser function apache_pw_hash

- lib/puppet/parser/functions/apache_pw_hash.rb
the apache_pw_hash function tests fail on puppet 4.7.1 because of 'uninitialized constant Base64'. Base64 is ruby stdlib, not core, so this requires it defensively.
> (maint) require base64

- manifests/init.pp
- manifests/mod/authnz_ldap.pp
- manifests/mod/negotiation.pp
- manifests/mod/ssl.pp
- manifests/vhost.pp
This completes the work https://github.com/puppetlabs/puppetlabs-apache/pull/1621 started. I think this covers all deprecation warnings.
Also makes puppet-lint a bit happier
> Use puppet 4 types to avoid deprecation warnings

- README.md
Adding documentation for the overrides param for apache::mod::userdir.
Also removing ' to solve a formatting issue.
> (MODULES-5324) Adding documentation for overrides

- README.md
- manifests/mod/jk.pp
- spec/classes/mod/jk_spec.rb
- templates/mod/jk.conf.erb
- templates/mod/jk/uriworkermap.properties.erb
- templates/mod/jk/workers.properties.erb
Current state: includes `mod_jk` module, creates jk.load, jk.conf and worker properties files and adds some description in the README file.
Lacks (as far as my creativity goes): parameter validation, proper parsing of some parameters, worker map file management and tests.
> [Modules 4746] Creates class for managing Apache mod_jk connector

- manifests/fastcgi/server.pp
- manifests/vhost.pp
- spec/defines/fastcgi_server_spec.rb
This and https://github.com/puppetlabs/puppetlabs-apache/pull/1664 should remove all deprecation warnings users might see.
> Replace deprecated type checking with Puppet 4 types

- README.md
Since there has repeatedly been some confusion with respect to
overriding the `default` and `default_ssl` vhosts in apache, add
some documentation explaining what is and isn't possible and a
potential workaround. See MODULES-5193 for more details.
> (MODULES-5458) Add docs for default vhost workaround

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
previously, when redirectmatch_* parameters were included, the RedirectMatch directive would be added to the vhost without mod_alias loaded. Since RedirectMatch is part of mod_alias, mod_alias is required. This change makes sure this happens whenever any of the three parameters are used.
> (MODULES-3942) make sure mod_alias is loaded with redirectmatch

- manifests/vhost.pp
recently, $directories in vhost.pp was puppet4-ized. because we still support Apache 2.2, we need to continue to allow $directories to have nested arrays so that users can pass arrays of allow/deny rules for each directory.
> (maint) allow arrays of arrays for $directories

- README.md
- manifests/mod/macro.pp
Adds `apache::mod::macro`.
https://httpd.apache.org/docs/trunk/mod/mod_macro.html
> Adds apache::mod::macro

- spec/classes/apache_spec.rb
- spec/classes/mod/userdir_spec.rb
- templates/mod/userdir.conf.erb
Some changes were made to the userdir.pp to allow for custom paths in #1650. This updates the template to use the custom string not only for the UserDir directive but also the Directory path.
related to #1682
> (maint) update userdir template

- README.md
- manifests/params.pp
- spec/acceptance/apache_ssl_spec.rb
- templates/vhost/_ssl.erb
If `$ssl_certs_dir` defaults to a location that contains certificates, apache will trust implicitly all the certificates presented by the client for auth that were issues by *any* certificates in that location. Setting the default to the location where all root certificates is stored enabled anyone with a key and cert from any of the SSL certificate provider to connect.
Note: 
* In Gentoo, `$ssl_certs_dir` was pointing to /etc/apache2/ssl, which may have been safe, or used for storing CA certs to check client auth. Gentoo users may need to set that value explicitly depending on how it was used in prior versions.
For more details, see [MODULE-5471]
> Setup SSL/TLS client auth without overly broad trusts for client certificates

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_passenger.erb
Currently, you can set this globally, but not per vhost...
It is supported in vhost context by passenger: https://www.phusionpassenger.com/library/config/apache/reference/#passengerspawnmethod
> Add passenger_spawn_method to vhost

- lib/facter/apache_version.rb
* `/` not being a special char, there is no need to escape it (removed preceding `\`);
* `.` matching *any* char, escaping it is required so that it matches a dot char (added preceding `\`).
> (maint) Improve version matching fact

- metadata.json
Removing Debian 6 from metadata. According to
https://docs.puppet.com/pe/latest/sys_req_os.html Debian 6 is no longer
supported.
> (maint) - Removing Debian 6 Support

- manifests/mod/prefork.pp
- spec/classes/mod/prefork_spec.rb
- templates/mod/prefork.conf.erb
MaxClients is now MaxRequestWorkers and MaxRequestsPerChild is now MaxConnectionsPerChild. This updates the manifest, template, and adds a couple unit tests. Unit tests for every OS did not seem necessary since all that is being tested is an if block.
> (MODULES-2062) updates prefork.conf params for apache 2.4

- manifests/mod/prefork.pp
- templates/mod/prefork.conf.erb
worker module has $listenbacklog          = '511',
event module has $listenbacklog          = '511',
I use prefork and I would like to use listenbacklog too.
> Added listenbacklog to prefork module

- README.md
- manifests/mod/passenger.pp
- spec/acceptance/mod_passenger_spec.rb
- spec/classes/mod/passenger_spec.rb
- templates/mod/passenger.conf.erb
Support for the available server configuration settings is currently incomplete.  The changes I've will:
- Add support for all currently documented server config settings
- Maintain support for the current set of apache::mod::passenger settings
- Check if the user provided version of passenger supports, deprecated or removed the server config setting, Note: only works if passenger_installed_version is set.
- Add basic rspec tests for the changes
- Add basic acceptances tests to validate the support, deprecated, and removed functionality
Items from the guidlines for contributing:
> MODULES-5426 : Add support for all mod_passenger server config settings	

- .travis.yml
Set the maximum parallel test processors to 16, to reduce the load on the Travis servers and prevent tests from being killed.
(This is needed in order for the tests for #1659 to not fail, but is not directly related to that PR, so I'm introducing it in an independent PR)
> Reduce Travis test parallelism

- README.md
There are a few inconsistencies in README.md in respect to arrays:
1. Sometimes, the arrays are quoted, and sometimes not.  Resolution: do not quote arrays.
2. Sometimes, there are spaces inside the angle brackets, sometimes not. Resolution: do not use space.
The choices where based on the most often used style.
> Improve style consistency in README.md

- spec/defines/vhost_spec.rb
Tests gave warnings about using raise_error without specifying the error type. This adds the types to suppress the warning.
> Added specific RSpec::Expectations::ExpectationNotMetError exeception

- spec/spec_helper_acceptance.rb
Tasks only work on builds with a puppet agent version of 5 or greater.
Adding logic to skip the task setup.
> Dont run task setup on LTS

- manifests/mpm.pp
This PR superseeds #1699 and #1713 
It does basically the same as #1699 but 
* without introducing fact operatingsystemmajrelease instead it uses operatingsystemrelease so the tests do not have to be altered…
* using versioncmp for robustness
> [MODULES-5644] Package name is libapache2-mpm-itk for Debian 9

- templates/httpd.conf.erb
This change will ensure that apache logs the correct client ip instead of the loadbalancer ip when the apache server is behind a load balancer
> updated log formats to include client ip

- .sync.yml
- .travis.yml
Set the environment variable `PARALLEL_TEST_PROCESSOR` in the global `env` section to avoid overloading the Travis testing containers and killing the tests.
Also add this to `.sync.yml` so it will be permanent (unlike my previous attempt at this).
> #puppethack Reduce Travis test parallelism, take 2

- README.md
Minor README.md tweak for php_values, along with example usage.
> Make section discussing php_values parameter a little more clear.

- manifests/mod/cgi.pp
This commit: https://github.com/puppetlabs/puppetlabs-apache/commit/0dcfa2a0109fc98a5fae76fb55cc9f4dbbb1c48c#diff-2c378354f8ec309dd88357170e38035d
Breaks a common setup of setting  $::apache::mpm_module to false and declaring your own mpm module to set params etc. and results in the following error:
```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Left match operand must result in a String value. Got a Boolean. at /etc/puppetlabs/code/environments/production/modules/apache/manifests/mod/cgi.pp:5:10
```
This restores that functionality while still maintaining the intent of the original commit.
The net effect should be the same, but it handles more cases better.
> Fix case of setting apache::mpm_module to false

- templates/vhost/_auth_cas.erb
Fix `templates/vhost/_auth_cas.erb` to create the proper `CASScrubRequestHeaders` setting when passed `@cas_scrub_request_headers`, rather than (re-)creating `CASAttributeDelimiter`.
> Actually create CASScrubRequestHeaders setting in _auth_cas.erb

- README.md
- manifests/params.pp
According to README, $keepalive is off by default but only RedHat and Amazon are set to on.
> Set default keepalive to on in all distros

- README.md
- manifests/init.pp
- manifests/vhost.pp
- spec/classes/apache_spec.rb
- spec/defines/vhost_spec.rb
- templates/httpd.conf.erb
- templates/vhost/_use_canonical_name.erb
apache and apache::vhost support for UseCanonicalName. This directive
controls how Apache uses self-referential URLs.
> Support for UseCanonicalName On | on | Off | off | DNS | dns

- README.md
- manifests/mod/ldap.pp
- spec/classes/mod/ldap_spec.rb
- templates/mod/ldap.conf.erb
* New param `$ldap_trusted_mode` adding to the `apache::mod::ldap` sub-module.
> (MODULES-5148) - Add `ldap_trusted_mode` parameter to mod_ldap config

- manifests/mod/remoteip.pp
Otherwise service is restarted even if service_manage=false
Signed-off-by: Sergii Kipot <kipot.sergey@gmail.com>
> remoteip: Notify apache::service instead of service['httpd']

- README.md
- manifests/mod/itk.pp
- spec/classes/mod/itk_spec.rb
- templates/mod/itk.conf.erb
Recently epel has updated the mod_itk package for RedHat:  https://bugzilla.redhat.com/show_bug.cgi?id=1432881
They have compiled with Linux capabilities support, which is enabled by default.
This breaks many existing setups that were using nfs etc that does not support Linux capabilities.
This adds the ability to turn off Linux capabilities and restore functionality on these setups.
> Add enable capabilities to itk

- README.md
- manifests/balancer.pp
- spec/defines/balancer_spec.rb
- New param `$options` to `apache::balancer` defined type so that it is
possible to create Proxy block such as:
```puppet
<Proxy balancer://foobar timeout=4 nonce=none>
BalancerMember ajp://spam:8009 retry=30
...
</Proxy>
```
> MODULES-5452 - add $options to `balancer` type

- README.md
- manifests/mod/python.pp
- spec/classes/mod/python_spec.rb
This is a work around to a particular clash between these
two lines.
```puppet
class{'apache::mod::python':}
class{'collectd::plugin::python':}
```
Both classes create a file resource `file{'python.load':}`
This patch allows the resource name to be configured for
`apache::mod::python` setup.
There is an altenative more perfect solution to use a better
more unique name space by default e.g `file{"apache_${_loadfile_name}:` but this
would touch so many test files....
This change is fully backwards compatible.
* [collectd::plugin::python](https://github.com/voxpupuli/puppet-collectd/blob/master/manifests/plugin.pp#L16)
> Expose loadfile_name option to mod::python class

- manifests/mod/ldap.pp
- spec/classes/mod/ldap_spec.rb
I consider config file for apache mod ldap `file` resource to have an "out of scope" name `ldap.conf` which may collide with the client-side config file ldap.conf (i.e. located in `/etc/ldap.conf` or `/etc/openldap/ldap.conf`).
My suggestion: renaming this file resource into `apache-mod-ldap.conf` in `manifests/mod/ldap.pp` and into the related `spec/classes/mod/ldap_spec.rb` file.
Here is the link to the [JIra issue](https://tickets.puppetlabs.com/browse/MODULES-6224)
> MODULES-6224: rename apache mod ldap file

- README.md
- manifests/mod/status.pp
- spec/classes/mod/status_spec.rb
- templates/mod/_allow.erb
- templates/mod/_require.erb
- templates/mod/status.conf.erb
In the current state, creates helper templates `mod/_allow` and `mod/_require` with, respectively, Apache 2.2 and 2.4 host authorization logic. These aim to be used by various templates in `mod/`. Then, template `mod/status.conf.erb` is modified to use one of these helper templates depending on Apache version.
The `_require` helper template implements "Require" directives from the parameter `requires` provided by the calling class. If this is `undef`, then uses variable `requires_defaults`, also provided by the calling class. In order not to break existing systems, if `requires == undef` but `allow_from` is defined, uses the latter and issue a deprecation warning.
`requires` parameter can be either of:
- `undef`
- '' or 'unmanaged' (No "Require" directive)
- String (`ip <list>`, `host …
> [Modules 5385] Include support for Apache 2.4 mod_authz_host directives in apache::mod::status

- README.md
- manifests/init.pp
- spec/acceptance/apache_parameters_spec.rb
- templates/httpd.conf.erb
Hello,
I need to configure this parameter : LimitRequestFields (http://httpd.apache.org/docs/current/mod/core.html#limitrequestfields) but it is not managed by your module yet.
So I took the liberty to add this parameter in the init.pp file (with a value at '100', which is the default value in apache) and in the httpd.conf template.
Successfully tested on Debian 8.9 and apache 2.4.10.
Thanks
> Add LimitRequestFields parameter in main configuration

- lib/puppet/functions/apache/apache_pw_hash.rb
- lib/puppet/functions/apache/bool2httpd.rb
- lib/puppet/functions/apache/validate_apache_log_level.rb
- manifests/init.pp
- manifests/vhost.pp
- spec/functions/apache_pw_hash_spec.rb
- spec/functions/bool2httpd_spec.rb
- spec/functions/validate_apache_log_level_spec.rb
- templates/httpd.conf.erb
- templates/mod/cluster.conf.erb
- templates/mod/expires.conf.erb
- templates/mod/geoip.conf.erb
- templates/mod/ssl.conf.erb
- templates/mod/wsgi.conf.erb
- templates/vhost/_directories.erb
- templates/vhost/_passenger.erb
- templates/vhost/_ssl.erb
The legacy puppet3 functions-api should be avoided.
This migrates the existing functions to the new api and uses it in the module. It also adds the tests for the new functions based on those for the olds.
We should keep the legacy functions for now to allow compatibility for those using the functions outside out this module.
> use of puppet4 functions-api

- spec/acceptance/vhost_spec.rb
- spec/spec_helper_acceptance.rb
The shibb package is not in the default repos; broken by #1657
On Dec 12th 2017 travis-ci updated their trusty environment and disabled
ipv6. This causes ipv6 tests to fail.
> (maint) Disable shibb testing on redhats and ipv6 testing without ipv6

- spec/spec_helper_acceptance.rb
[A change in the new beaker-task_helper uses versioncmp.](https://github.com/puppetlabs/beaker-task_helper/pull/16) Therefore adding
a puppet requirement in the spec_helper_acceptance to access versioncmp.
> (MODULES-6608) - Adding puppet requirement for tasks versioncmp in beaker-task_helper

- README.md
- manifests/mod/jk.pp
- readmes/README_ja_JP.md
- spec/classes/mod/jk_spec.rb
- templates/mod/jk/workers.properties.erb
Fix key 'worker_mantain' in $workers_file_content
- Add spec tests for advanced mod_jk configuration
- Fix *worker_mantain* typo (see below)
- Call `fail()` function when using the deprecated *worker_mantain* key
Original comment in worker.properties.erb reference a key
*worker_mantain* in the `$workers_file_content` hash.
From the original Apache's mod_jk documentation [1], the parameter name is
`worker.maintain` and has been mistyped as `worker.mantain` (note the
missing *i* letter).
[1] https://tomcat.apache.org/connectors-doc/reference/workers.html
Here is the [Reference in Jira](https://tickets.puppetlabs.com/browse/MODULES-6225)
> MODULES-6225 :  fix worker mantain typo

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_passenger.erb
Just like we can use `passenger_user` in a VHost, allow setting `passenger_group`.
> Allow overriding passenger_group in apache::vhost

- examples/vhost.pp
These SSL settings are worse than the default one:
- It only enables TLS1, no 1.1 or 1.2
- It enables RC4, which is supposed to be forbidden nowadays (http://www.ietf.org/rfc/rfc7465.txt)
> Remove insecure/bad SSL example

- .travis.yml
When using the pdk all additional configurations are put into the `.sync.yml` Currently there is no method to put this in the `.sync.yml` and populate via the pdk-template. Manually adding back in and have a ticket on the backlog to address this issue.
> (maint) - Re-adding PARALLEL_TEST_PROCESSORS

- lib/facter/apache_version.rb
The fact was confined in 783729a5f2e348a4728f3ce29f0b58c7e0a425dd but running the test suite on FreeBSD will fail because the fact is confined to Linux.
Instead of simulating Linux when testing on FreeBSD, enable the fact on FreeBSD so that the apache version is available in Puppet manifests on this platform.
> Re-enable the apache_version fact on FreeBSD

- README.md
Updates the documentation to match the code, which already is in line with Apache's default. Discussed briefly here: https://tickets.puppetlabs.com/browse/DOCUMENT-870
> (DOCUMENT-870) Updates ssl_proxyengine default

- README.md
According to the apache documentation https://httpd.apache.org/docs/2.4/rewrite/remapping.html a $ sign is need before the numbered replacment param in the redirectmatch section.
Mine is working with the $ sign. I did not test without.
> added $ to replacment param

- README.md
- manifests/mod/auth_gssapi.pp
- manifests/params.pp
- spec/classes/mod/auth_gssapi_spec.rb
mod_auth_gssapi has a similar functionality to mod_auth_kerb, and is the
recommended way to deploy authorization with kerberos, through GSSAPI.
This merely adds the necessary module.
> Add mod::auth_gssapi manifest

- README.md
- manifests/init.pp
- manifests/mod.pp
- spec/classes/mod/wsgi_spec.rb
This commit allows to override 'mod_libs' similar to how 'mod_packages'
is currently overriden. All the references to apache::params::mod_libs
are changed to apache::mod_libs.
> MODULES-7343: Allow overrides by adding mod_libs in apache class

- manifests/init.pp
- manifests/mod/proxy.pp
- templates/mod/proxy.conf.erb
Separately changes the default for Timeout to the Apache default per this discussion. https://tickets.puppetlabs.com/browse/MODULES-5792.
> Add support for ProxyTimeout

- spec/acceptance/mod_passenger_spec.rb
This typo is present since ~ 7 months. https://github.com/puppetlabs/puppetlabs-apache/commit/02919a8295b31931efda728654ab1d69ac4771e7#diff-54659813dfca25ca1f5df88aaccb09ecL199
Nobody noticed it because there are no acceptance tests running for
everything where unless does not match. I discovered this in https://github.com/puppetlabs/puppetlabs-apache/pull/1809
> fix typo in the tests

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_file_header.erb
You can pass
```puppet
comment => 'My comment',
```
or
```puppet
comment => [
'comment 1',
'comment 2',
],
```
Each element from the array will be added as a separate line.
> Add option to add comments to the header of a vhost file

- README.md
The README.md still references the old `15-` value as default in some places. This PR fixes that and changes it to the `25-` default.
> Fix default vhost priority in readme

- manifests/mod/dav_svn.pp
- manifests/mod/security.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/mod_dav_svn_spec.rb
- spec/acceptance/mod_passenger_spec.rb
- spec/acceptance/mod_php_spec.rb
- spec/acceptance/mod_security_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/spec_helper_acceptance.rb
Updated default params added.
Exclusions added for certain features.
> (MODULES-8108) - Support added for Debian 9

- README.md
The anchor tag helps fix broken links — If the header text changes (gets localized) the link will brake.
> (maint) Add HTML anchor tag

- manifests/mod/remoteip.pp
- spec/classes/mod/remoteip_spec.rb
- templates/mod/remoteip.conf.epp
The recent addition of data types for this module [1] introduced an
issue, where CIDRs are no longer allowed. This allows those sort of
values.
This addresses https://tickets.puppetlabs.com/browse/MODULES-8731
[1] https://github.com/puppetlabs/puppetlabs-apache/commit/1503035d788f9fdaa2bab9cdaabfb66e858c2c39#diff-c2ea3c67760696a0d67bab9fb81757c6
> (MODULES-8731) Allow CIDRs for proxy_ips/internal_proxy in remoteip

- README.md
- manifests/init.pp
- manifests/mod/http2.pp
- manifests/vhost.pp
- spec/classes/mod/http2_spec.rb
- spec/defines/vhost_spec.rb
- templates/httpd.conf.erb
- templates/mod/http2.conf.erb
- templates/vhost/_directories.erb
- templates/vhost/_file_header.erb
- templates/vhost/_http2.erb
[`mod_http2`](https://httpd.apache.org/docs/current/mod/mod_http2.html) was introduced in Apache 2.4.17 and provides HTTP/2 ([RFC 7540](https://tools.ietf.org/html/rfc7540)) support.
This pull request allows configuring HTTP/2 websites using the apache module.
> Add support for mod_http2

- manifests/default_mods.pp
- manifests/mod.pp
- manifests/params.pp
Rebase of PR ('https://github.com/puppetlabs/puppetlabs-apache/pull/1845') made to add compatibility for Amazon Linux 2, thank you @engshine for the work that you have done.
The changes on this PR all originate from @engshine.
Please note that this does not mean that Amazon Linux 2 is supported.
> (feat) - Amazon Linux 2 compatibility added

- manifests/vhost.pp
This pull request fixes a problematic situation regarding logging.
Specifically, when Apache service starts up, it opens log files (e.g.,`/var/log/apache2/access.log`) through the following system call:
```
open("/var/log/apache2/access.log", O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC) = 7
```
While Apache service is up, those files remain open for efficiency.
Consider this scenario: If the log directory (i.e, `/var/log/apache2`) misses from the host, applying the catalog creates the directory again. The issue is that the service is unaffected. Specifically, the Apache server still handles a file descriptor that corresponds to the original log file (`/var/log/apache2/access.log`), i.e., the open file descriptor points to the inode which the initial log file was pointing to.
When we remove a …
> Logging bug: prevent upcoming log events from getting lost

- README.md
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_wsgi.erb
The README states wsgi_daemon_process is a hash data type however the
ERB template interpolates it as a string. As this type it currently
cannot accept multiple daemon processes per vhost, and requires
wsgi_daemon_process_options to manage parameters.
This commit adds logic to the parameter to support this data type while
maintaining original functionality. The data type allows for multiple
daemons per vhost, and deprecates wsgi_daemon_process_options.
> Fix wsgi_daemon_process to support hash data type

- REFERENCE.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
- Add a stapling_cache parameter to apache::mod::ssl
* if it is set to undef (the default value), the actual behavior will
take place (SSLStaplingCache will be set to a value based on the OS)
* if is is set to a string, this string will used as a value for
SSLStaplingCache.
- Adapt template ssl.conf.erb accordingly
- Add unit tests got the stapling_cache parameter
- Document the stapling_cache parameter
> (MODULES-9018) Customize SSLStaplingCache parameter

- REFERENCE.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
Add the boolean parameter ssl_sessiontickets to apache::mod::ssl
Use parameter ssl_sessiontickets in ssl.conf.erb
Add unit tests for parameter ssl_sessiontickets
Document the parameter ssl_sessiontickets
> (MODULES-9014) Add SSLSessionTickets parameter

- REFERENCE.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
- Make ssl_sessiontickets parameter optional
- Set default value for ssl_sessiontickets to undef (Compatible
with all Apache versions)
- Update documentation and unit tests accordingly
@sheenaajay Here the the pull request with the fixes you expected.  ssl_sessiontickets is now optional with the default value set to undef. So, by default, the parameter will not be set and nothing will break on older distributions.  Moreover it simplifies the code, which is always a good thing.
> (MODULES-9014) Improve SSLSessionTickets handling

- manifests/custom_config.pp
- manifests/init.pp
- manifests/mod/reqtimeout.pp
- `::apache::file_mode` attribute is missing from several config files, including the main config file in `::apache`, any custom config files managed by `apache::custom_config`, and reqtimeout.conf managed by `apache::mod::reqtimeout`
- Add `mode => $::apache::file_mode` to `::apache`, `apache::custom_config`, and `apache::mod::reqtimeout` to correct the inability to manage the mode of these config files.
> (MODULES-9104) Add file_mode to config files.

- manifests/init.pp
- templates/httpd.conf.erb
If you need to specify these parameters for, as an example, connecting to Active Directory using ldaps
> Add LDAP parameters to httpd.conf

- manifests/mod/userdir.pp
- spec/classes/mod/userdir_spec.rb
- templates/mod/userdir.conf.erb
The unmanged_path option stops the template from configuring the directory permissions in userdir.conf, this is useful if you want to have path set as 'public_html' or 'https://mysite/*' etc.
The custom_fragment option allows you to add your own config to userdir.conf, useful when using the unmanaged_path option.
> Added unmanaged_path and custom_fragment options to userdir

- CHANGELOG.md
- HISTORY.md
- REFERENCE.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
This fork and change makes 'ProxyRequests' in Apache vhost sections managed by puppetlabs-apache configurable. I created a Jira ticket as well (MODULES-9668)
> (MODULES-9668 ) Please make ProxyRequests setting in vhost.pp configurable

- metadata.json
- provision.yaml
- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/default_mods_spec.rb
- spec/acceptance/itk_spec.rb
- spec/acceptance/prefork_worker_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/classes/mod/passenger_spec.rb
- spec/classes/mod/security_spec.rb
- spec/defines/fastcgi_server_spec.rb
- spec/defines/vhost_spec.rb
- spec/spec_helper_acceptance_local.rb
> FM-8140 Add Redhat 8 support

- spec/acceptance/apache_ssl_spec.rb
- templates/vhost/_ssl.erb
This is a solution to solve the bug I have submitted ([MODULES-9083](https://tickets.puppetlabs.com/browse/MODULES-9083)).
I hope it can help.
It is a rebase onto master of this [PR 1920](https://github.com/puppetlabs/puppetlabs-apache/pull/1920). Thus, the PR1920 can be cancelled.
Best Regards
> MODULES-9083: remove double quotes to allow flags in SSLCARevocationCheck

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
This PR adds support for the [LDAPReferrals](https://httpd.apache.org/docs/2.4/mod/mod_ldap.html#ldapreferrals) parameter. I could not find any documentation regarding all the possible values for the `directories` hash. If I missed this, I will add some documentation.
> Add LDAPReferrals configuration parameter

- manifests/vhost.pp
- templates/vhost/_file_footer.erb
- templates/vhost/_file_header.erb
The variable can them be used inside the vhost tag as a variable.
At the footer, the variable is undefined to avoid side effects
in other vhosts.
also see https://httpd.apache.org/docs/2.4/mod/core.html#define
> add possibility to define variables inside VirtualHost definition

- manifests/params.pp
Debian renamed the shib library to mod_shib.so in Debian 10 (buster) so mod shibboleth won't load anymore. This PR fixes that.
> Add shibboleth support for Debian 10

- manifests/custom_config.pp
We use `apache::custom_config` for files that contain secrets like mod_auth_openidc so this has become necessary and would be ideal not to have to do this:
```puppet
::apache::custom_config { 'auth_openidc':
content        => template('openondemand/apache/auth_openidc.conf.erb'),
priority       => false,
}
File <| title == 'apache_auth_openidc' |> {
owner     => 'root',
group     => 'apache',
mode      => '0640',
show_diff => false,
}
```
> Add owner, group, file_mode and show_diff to apache::custom_config

- README.md
As `mod_fastcgi` is not longer supported, the actual doc is incorrect. This PR adds a subsection for Ubuntu 18.04.
Dear maintainers, this is my first PR on this project. I've read the contributing guidelines, and tried to follow them. Feel free to comment / amend :)
> FIX FastCGI doc on Ubuntu 18.04

- manifests/mod/security.pp
- manifests/params.pp
- spec/classes/mod/security_spec.rb
We want to be able to select mod security 1 or 2.
Depending on Version, package names and config files are different.
Fixes: https://tickets.puppetlabs.com/browse/MODULES-9947
> Add parameter version for mod security

- manifests/balancer.pp
Under recent apache versions (not sure when changed, but certainly
in 2.4.34), the lbmethod modules depend on symbols present in either
the mod_proxy or mod_proxy_balancer modules. Prior to this commit,
this module creates an `lbmethod_${method}.load` file which comes
alphabetically before `proxy.load` and `proxy_balancer.load`.
Under these recent apache versions, the daemon will therefore fail
to configtest or startup due to the invalid configuration.
This commit adjusts the module load order so that the lbmethod module
is loaded after those its dependent upon.
> MODULES-9904 Fix lbmethod module load order

- manifests/mod/ssl.pp
There were Pipelines CI test failures being caused by Apache not being able to load the SSL module on SLES 11: 
https://pipelines.puppet.com/team-modules/builds/599671
```ruby
2) apache::vhost define parameter tests applies cleanly
On host `j3ye05rmc16s212.delivery.puppetlabs.net'
Failure/Error: apply_manifest(pp, catch_failures: true)
RuntimeError:
apply manifest failed
` puppet apply /tmp/manifest_20191029_43621_1a8n2bk.pp --detailed-exitcodes`
with exit code 6 (expected: [0, 2])
====== Start output of failed Puppet apply ======
Warning: Scope(Class[Apache::Mod::Prefork]): For newer versions of Apache, $maxclients is deprecated, please use $maxrequestworkers.
Error: /Stage[main]/Apache::Service/Service[httpd]: Failed to call refresh: Could not restart Service[httpd]: Execution of …
```
> (FM-8662) Correct  in manifests/mod/ssl.pp for SLES 11

- manifests/mpm.pp
- manifests/mpm/disable_mpm_event.pp
- manifests/mpm/disable_mpm_prefork.pp
- manifests/mpm/disable_mpm_worker.pp
- spec/classes/apache_spec.rb
On Debian based systems (I have not tested behavior on other OS) you can have multiple thread modules installed in parallel. An admin must ensure that only one thread module is active by disabling any old thread module when adding a new one.
Changing thread module was not possible in Puppet Apache Module.
Once a thread module was active it never got disabled when switching to another one, causing the apache process to not be able to start.
This PR adds the capability to switch thread modules on existing, Puppet managed apache installations on Debian based systems.
Usual thread modules are: prefork, event or worker.
When switching from one thread module to another we must ensure that the
old, no longer to use, thread module gets disabled.
Puppet Apache module will always use the new mpm …
> (MODULES-9948) Allow switching of thread modules

- manifests/mod/ssl.pp
- manifests/params.pp
- spec/acceptance/mod_php_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/classes/mod/php_spec.rb
Request for a review
Fixed the following
Updated the PHP default version from 5 to 7 for redhat8 
Updated the unit test cases for the verification
Fixed the SSL certificate error on redhat8. The protocol is removed for security reasons.
Testcases run on release checks and all are running clean.
> (FM-8721) fix php version and ssl error on redhat8

- manifests/mod/security.pp
This PR moves the unless block inside the manage manage_security_corerules block because it is only needed if core rules are there. It also prevents the apache::security::rule_link define to be called if security core rules are not managed
> move unless into manage_security_corerules

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
When a proxy_pass with additional params is defined within a directories location entry, the params get appended in a new line (which breaks config).
The change in this pull request removes the superfluous newline.
> Fix newline being added before proxy params

- manifests/vhost/fragment.pp
- spec/defines/vhost_fragment_spec.rb
The apache::vhost::fragment define allows adding fragments to an existing vhost. This is easier than using the custom_fragment property, especially when one class defines the vhost and another class wants to add add some content to that.
This work was inspired by https://github.com/puppetlabs/puppetlabs-apache/pull/1659.
> Add an apache::vhost::fragment define

- REFERENCE.md
- manifests/mod/ssl.pp
- manifests/params.pp
- spec/acceptance/apache_ssl_spec.rb
- spec/classes/mod/ssl_spec.rb
- spec/spec_helper_acceptance_local.rb
(Reported as MODULES-10391)
The default for the `apache::mod::ssl_protocol` parameter was changed to allow SSLv2 and SSLv3 on all platforms, which isn't desirable on anything with an older version of OpenSSL.  Noticed on CentOS 7 hosts after upgrading this module, without changing any parameters.
Hence this PR is to move the default setting to the params class and only set it for RHEL 8, which appears to be in the intention of the prior change in FM-8721 (PR #1691 
This then fixes this regression on other platforms.
> (MODULES-10391) ssl_protocol includes SSLv2 and SSLv3 on all platforms

- manifests/mod/autoindex.pp
- templates/mod/autoindex.conf.erb
Icon paths in autoindex.conf.erb are not correct on systems with @osfamily == 'RedHat' or @osfamily == 'Suse'.
The proposed patch removes the filename suffix '-20x22' on those systems.
This way compatibility with systems noted in metadata.json is ensured.
The proposed patch would solve: https://tickets.puppetlabs.com/projects/MODULES/issues/MODULES-10360?filter=allissues
Thank you for your time and effort.
> (MODULES-10360) Fix icon paths for RedHat systems

- manifests/vhost.pp
When using "SSLProxyEngine On" in virtualhost config it has to be ordered before any Proxy-directive using it. 
Otherwise httpd is complaining about SSLProxyEngine not being enabled…
> SSLProxyEngine on has to be set before any Proxydirective using it

- manifests/mod/security.pp
- manifests/params.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
- Add new parameter and update security.conf template to enable configuration of ModSecurity [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secauditlogtype)
- Add new parameter and update security.conf template to enable configuration of ModSecurity [SecAuditLogStorageDir](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secauditlogstoragedir)
- Add tests for new parameters and defaults
> Add template variables and parameters for ModSecurity Audit Logs

- manifests/mod/proxy_html.pp
In https://github.com/puppetlabs/puppetlabs-apache/commit/8e7ef1550cc8a4f816a0f4d7235df36b48664998 a fix was made to support Ubuntu 10.04, where libxml2 is at another location.
But since the "case"-clause is using $::osfamily as parameter it now matches on Debian 10 too.
This fix implements the distinction between Debian and Ubuntu systems.
> Fix proxy_html Module to work on Debian 10

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_file_header.erb
Added deirectives LimitRequestBody, LimitRequestFields, LimitRequestFieldSize
and LimitRequestLine
> [MODULES-10530] Add request limiting directives on virtual host level

- manifests/params.pp
I'm not sure why this was ever removed. See #1932 
* https://packages.debian.org/buster/libapache2-mod-fcgid
* https://packages.ubuntu.com/eoan/libapache2-mod-fcgid
> Re-add package for fcgid on debian/ubuntu machines

- manifests/mod/ldap.pp
- spec/classes/mod/ldap_spec.rb
Otherwise no symlink for the ldap.conf is created in /etc/apache2/mods-enabled as required by mod.pp. Thus the custom ldap options in the /etc/apache2/mods-available are not applied in the /etc/apache2/mods-enabled and are not loaded.
> Changed the apache-mod-ldap.conf title to ldap.conf

- manifests/mod/proxy.pp
- templates/mod/proxy.conf.erb
Add [ProxyIOBufferSize](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyiobuffersize) for `mod_proxy`
Found we need to adjust this in combination w/ AJP to account for larger headers (cookies)
> Add ProxyIOBufferSize option

- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/itk_spec.rb
- spec/acceptance/vhost_spec.rb
There are a number of issues against the `puppetlabs-apache` module that are either been actively worked upon or have tickets raised to be worked on:
**[IAC-587](https://tickets.puppetlabs.com/browse/IAC-587)**: mod_auth_openidc module is not installing correctly on RHEL 8.x systems
**[IAC-785](https://tickets.puppetlabs.com/browse/IAC-785)**: Shibboleth module not configuring correctly on Debian 10 systems
**[IAC-787](https://tickets.puppetlabs.com/browse/IAC-787)**: httpd-itk module not available from main repos on RHEL 8 and CentOS 8
There have been a number of new features merged to the branch and other PRs waiting to be merged. A new release of the module is overdue too, so this PR is simply to back out these tests and unblock the release.
The functionality affected should be …
> (maint) Restrict test exec platforms for accept tests affected by IAC-587, IAC-785 & IAC-787

- manifests/mod/remoteip.pp
- spec/classes/mod/remoteip_spec.rb
- templates/mod/remoteip.conf.epp
This is the same fix as in https://github.com/puppetlabs/puppetlabs-apache/pull/1891
> Allow IPv6 CIDRs for proxy_protocol_exceptions in mod remoteip

- manifests/mod/passenger.pp
Installation of passenger module fails on el systems because yum repo gpgkey  has been changed from `https://packagecloud.io/phusion/passenger/gpgkey`
to` https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt`
Reference:  
https://github.com/phusion/passenger/issues/2276
https://tickets.puppetlabs.com/browse/MODULES-10656
> update passenger yum repo gpgkey url

- Gemfile
They have been removed as they now live in puppet_litmus.
> Remove net-ssh dependency gems

- manifests/mpm.pp
- manifests/mpm/disable_mpm_event.pp
Extends #1961 to also work correctly on Debian 10 and Ubuntu 20
> Allow switching of thread module

- manifests/params.pp
- spec/classes/mod/passenger_spec.rb
- spec/classes/mod/security_spec.rb
- spec/classes/mod/ssl_spec.rb
Updating modules path, icons path, error documents path for CentOS 8. Without this patch, all the module .load and .conf files ended up in $confd_dir.
> Update mod_dir, alias_icons_path, error_documents_path for CentOS 8

- spec/spec_helper_acceptance_local.rb
After the recent introduction of the CentOS 8 platform to TravisCI's tests in https://github.com/puppetlabs/puppetlabs-apache/pull/2040, it caused a number of test failures as the test expectations were not updated with the common conf dirs for CentOS 8. This PR should not have been merged without the TravisCI tests executing.
See failing tests [here](https://travis-ci.org/github/puppetlabs/puppetlabs-apache/builds/701224969)
> (maint) Update test settings hash for CentOS 8 expectations

- spec/spec_helper_acceptance_local.rb
beff9916e26807d3d75462bda868d093225fac1a changed the logic, but in a very complicated way. This prefers to put the newest version first and fall back to older versions. That avoids multiple if conditions.
> (maint) Straighten up test settings for EL8

- spec/spec_helper_acceptance_local.rb
https://github.com/puppetlabs/puppetlabs-apache/pull/2042 fixed an issue with the apache_settings hash being set with incorrect expectations for RHEL 8.x systems. https://github.com/puppetlabs/puppetlabs-apache/pull/2043 attempted to improve upon that, but reverted the change made to set the 'mod_dir' for RHEL 8.x in https://github.com/puppetlabs/puppetlabs-apache/pull/2042 . Some CI test runner issues obsficated the break in both cases.
> (maint) Fix test expectations from bad PR merge

- manifests/params.pp
- spec/acceptance/mod_authnz_ldap_spec.rb
- spec/classes/mod/authnz_ldap_spec.rb
see https://tickets.puppetlabs.com/browse/MODULES-10586
the change was tested on a fresh centos 8 install
note on unit tests: 
- I edited the tests 'default configuration with parameters on a RedHat OS' in authnz_ldap_spec.rb and ldap_spec.rb (updated the facts operatingsystemrelease line to '8') in the puppetlabs module (not containing my change) 
- so those tests should have failed but didn't 
so I was unable to provide a sensible unit test
> MODULES-10586 Centos 8: wrong package used to install mod_authnz_ldap

- manifests/params.pp
- spec/acceptance/mod_ldap_spec.rb
https://github.com/puppetlabs/puppetlabs-apache/pull/1913 changed ldap package to always be mod_ldap, but on rhel/centos 5 and 6 mod_ldap is in the httpd package and there is no mod_ldap package.
> MODULES-10712 fix mod_ldap on RH/CentOS 5 and 6

- spec/acceptance/mod_authnz_ldap_spec.rb
This should eventually be moved to the spec_helper_acceptance_local before(:suite) steps when an official EPEL repo is available for RedHat and CentOS 8.x.
Also added a 'yum clean all' as the Oracle 7 hosts from VMPooler were sometimes encountering the following error:
```
Error downloading packages:
[Errno 256] No more mirrors to try.
```
> (maint) Add EPEL repo for RHEL 8 tests in mod_authnz_ldap_spec

- README.md
- spec/spec_helper_acceptance.rb
- spec/spec_helper_acceptance_local.rb
- spec/util/_resources/test_metadata_json.rb
- spec/util/apache_mod_platform_support_spec.rb
- util/_resources/tag_format_help_msg.txt
- util/apache_mod_platform_support.rb
We have been battling a long running issue with tests that use Apache MODs failing on certain Linux platforms whenever the package or package dependencies become available on a specific platform. This has been defined in [IAC-801](https://tickets.puppetlabs.com/browse/IAC-801). A number of recently raised JIRA tickets share the this root cause:
- **[IAC-790](https://tickets.puppetlabs.com/browse/IAC-790):** Missing dependencies for ldap_mod package on RHEL 7.x Docker containers
- **[IAC-787](https://tickets.puppetlabs.com/browse/IAC-787):** http-itk module not installing on RHEL 8.x systems
- **[IAC-587](https://tickets.puppetlabs.com/browse/IAC-587):** apache module failing with 'Cannot load /usr/lib64/apache2/mod_auth_openidc.so' on RHEL distros
Provide:
- The ability to tag Apache MODs …
> (IAC-824) Ability to exclude Apache MOD tests from unsupported platforms

- manifests/mod/authnz_ldap.pp
- spec/acceptance/vhost_spec.rb
Requires https://github.com/puppetlabs/puppetlabs-apache/pull/2036 to be merged first.
> (IAC-587) Tag apache::mod:authnz_ldap with unsupported platforms

- manifests/mod/authnz_ldap.pp
- manifests/mod/event.pp
- manifests/mod/itk.pp
- manifests/mod/ldap.pp
- manifests/mod/php.pp
- manifests/mod/shib.pp
- manifests/mod/wsgi.pp
- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/itk_spec.rb
- spec/acceptance/mod_authnz_ldap_spec.rb
- spec/acceptance/mod_ldap_spec.rb
- spec/acceptance/mod_php_spec.rb
- spec/acceptance/prefork_worker_spec.rb
- spec/acceptance/vhost_spec.rb
Using the functionality available after #2036 was merged to make the Apache MOD test exclusion a bit tidier.
> (IAC-934) Use tagging to filter Apache MOD tests from execution

- manifests/params.pp
The mod_wsgi package was renamed to python3-mod_wsgi on CentOS8, and
now the old name doesn't work since the provides and obsoletes for it
was removed[1].
[1] https://centos.pkgs.org/8/centos-appstream-x86_64/python3-mod_wsgi-4.6.4-4.el8.x86_64.rpm.html
> Use python3-mod_wsgi instead of mod_wsgi on CentOS8

- manifests/params.pp
This change makes sure that apache::version::distrelease is always used
to detect OS major version, instead of facts, so that the same logic is
used for the version detection.
> [CentOS] Always use distrelease to detect OS major versions

- lib/puppet/functions/apache/bool2httpd.rb
- spec/functions/bool2httpd_spec.rb
In Ruby 2.7, performing true =~ %r{false}i raises a deprecation warning.
> Use Ruby 2.7 compatible string matching

- manifests/params.pp
- spec/classes/mod/wsgi_spec.rb
RHEL8:
```
/usr/lib64/httpd/modules/mod_wsgi_python3.so
```
RHEL7:
```
/usr/lib64/httpd/modules/mod_wsgi.so
```
Tests might need to be changed. The package name selection has already been patched in commit [d346b76d1aab954b642c55942d3ff8cf6cb578ac](https://github.com/puppetlabs/puppetlabs-apache/commit/d346b76d1aab954b642c55942d3ff8cf6cb578ac).
> Configure default shared lib path for mod_wsgi on RHEL8

- README.md
- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/class_spec.rb
The `policycoreutils-python` has now been replaced by the `policycoreutils-python-utils`
on RHEL 8 according to [this documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#selinux-python3_security)
> (maint) Use 'policycoreutils-python-utils' on RHEL 8

- manifests/mod/jk.pp
- manifests/vhost.pp
Several lines in the comments of apache::vhost and apache::mod::jk have non-ascii characters embedded.  This can throw off some testing suites, such as Oneceover, which will complain about it.  This pull request replaces non-ascii characters with acceptable alternatives.
> Replace some occurrences of non-ASCII chars

- manifests/mod/fcgid.pp
before -> rhel 8, fcgid.load is loaded before unixd.load  which causes httpd to fail
So the name unixd_fcgid.load should also be implemented for rhel 8
> make apache::mod::fcgid redhat 8 compatible

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
- templates/vhost/_gssapi.epp
mod_auth_gssapi parameters can only used inside a directory section of a vhost.
Parameters are specified as a hash `gssapi` to the directories parameter.
Currently only the three obvious parameters are supported, adding extra ones is a
trivial addition to the `_gssapi.epp` template.
Example
```puppet
include apache::mod::auth_gssapi
apache::vhost { 'sample.example.net':
docroot     => '/path/to/directory',
{ path   => '/path/to/different/dir',
gssapi => {
credstore => 'keytab:/foo/bar.keytab',
localname => 'Off',
sslonly   => 'On',
}
},
],
```
These 3 values match to an apache configuration of
```config
<Directory /path/to/different/directory>
GssapiSSLonly Off
GssapiLocalName On
GssapiCredStore keytab:/foo/bar.keytab
</Directory>
``` …
> WIP: Support mod_auth_gssapi parameters

- REFERENCE.md
- manifests/vhost.pp
- templates/vhost/_sslproxy.erb
Added the Apache vhost proxy config option SSLProxyMachineCertificateChainFile.
Reference: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslproxymachinecertificatechainfile
> Add ssl_proxy_machine_cert_chain param to vhost class

- spec/defines/vhost_spec.rb
- types/oidcsettings.pp
This PR takes [psaiz's](https://github.com/psaiz) work in #2076 and also adds unit tests.
Closes #2076
> Allow relative paths in oidc_redirect_uri

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- templates/vhost/_access_log.erb
Prior to this commit, the `$filename` variable, which is used to
construct the filename of Apache's various config and log files,
obtained it's default value from the `$name` parameter.
As #2064 highlights, it is possible for `$name` to contain spaces
in it and this can cause cumbersome log file names, albeit POSIX
compliant.
Also related is #2068, which changes the `$filename` variable source
from `$name` to `$servername`. This arguably seems more appropriate,
especially given that `$servername` defaults to `$name` if undefined.
This commit attempts to create a satisfactory solution to both #2064
and #2068 by introducing the `$use_servername_for_filenames` param.
When set to `true`, a sanitized `$servername` parameter value will be
used to construct `$filename`.
When undefined or set to …
> (IAC-1186) Add new $use_servername_for_filenames parameter

- manifests/vhost.pp
- spec/acceptance/apache_ssl_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
- templates/vhost/_ssl.erb
Enable SSLVerifyClient and SSLVerifyDepth inside locations. Add SSLVerifyClient validation. SSLCACertificate (and related options) can now be specified even without SSLVerifyClient (can be inside a location).
> Improve SSLVerify options

- manifests/init.pp
The default vhost definitions are called without
`use_servername_for_filenames` being set, which leads to a deprecation
warning on every run.
With this PR, the parameters are added to the default entries and thus
avoid generating said error message.
This was verified on a local installation.
> (MODULES-10887) Set `use_servername_for_filenames` for defaults

- templates/mod/_require.erb
Single line warnings are better readable and greppable from server logs.
Fixes https://tickets.puppetlabs.com/browse/MODULES-8518
> (fix) Convert unnecessary multi line warnings to single lines

- manifests/mod/md.pp
- manifests/mod/watchdog.pp
- manifests/params.pp
- manifests/vhost.pp
- spec/acceptance/mod_md_spec.rb
- spec/classes/mod/md_spec.rb
- spec/classes/mod/watchdog_spec.rb
- spec/defines/vhost_spec.rb
- templates/mod/md.conf.epp
- templates/vhost/_file_header.erb
- templates/vhost/_ssl.erb
This PR add support for [mod_md](https://httpd.apache.org/docs/current/en/mod/mod_md.html), a module for managing domains across virtual hosts and certificate provisioning via the ACME protocol.
Each of these points have been added as a separate commit for clarity:
It brings full support for mod_md into the Apache module.
Support for the [\<MDomain\> sections](https://httpd.apache.org/docs/current/en/mod/mod_md.html#mdomainsetsection) is not part of this PR.  *\<MDomain\>* allows to override general configuration when requesting certificates from multiple providers.  This use case is rather advanced so I guess support for it can be skipped as of today.  Future contributors might be able to add support for this by allowing to pass an `Enum` to `$apache::vhost::mdomain` with all custom …
> Add support for mod_md

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_ssl.erb
Maps to SSLUserName directive.
> Add ssl_user_name vhost parameter

- .sync.yml
- Rakefile
This was primarily done to add the following line to the Rakefile:
`FastGettext.default_text_domain = 'default-text-domain'` and
prevent syntax checks failing because of the text domain is not
set (which generates a return code of 1).
> (MAINT) Perform pdk update

- manifests/params.pp
This corrects some module packages for Ubuntu 16.04. suphp was actually removed. The other packages are transitional packages. Using the modern ones aligns them with newer versions. It also greatly simplifies the params code.
> (FIX) Correct PHP packages on Ubuntu 16.04

- spec/classes/apache_spec.rb
- spec/classes/mod/authnz_ldap_spec.rb
- spec/classes/mod/data_spec.rb
- spec/classes/mod/peruser_spec.rb
- spec/classes/mod/php_spec.rb
- spec/classes/mod/remoteip_spec.rb
- spec/classes/mod/ssl_spec.rb
- spec/classes/mod/status_spec.rb
- spec/classes/mod/wsgi_spec.rb
Rather than checking the notify/require properties, it uses the matchers that check the dependency graph. That means it can also check transitive requires/notifies.
It also uses compile and compile.and_raise_error as a shorter way to check for errors (or the absense of them).
This is just a tiny improvement. The specs need a major update since a lot of the examples are using hardcoded facts of EOL OSes.
> Use the correct matches in rspec

- manifests/mod/php.pp
- manifests/params.pp
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/php_spec.rb
This PR incorporates the changes from https://github.com/puppetlabs/puppetlabs-apache/pull/2119 and https://github.com/puppetlabs/puppetlabs-apache/pull/2124 along with a few other additions:
- Change range of `versioncmp` to `< 8` to reduce churn in previous conventions for `7.x` PHP versions
- Enable and update acceptance test expectations for PHP mod packages on SLES 15. In hindsight, I'm not sure this was required after all, but I wanted to catch any potential issues around the changes being performed given SLES is a bit special with it's MOD PHP package names.
- Update test expectations for OSs using PHP >= 7 based on the new naming conventions in
> (MODULES-10899) Handle PHP8 MOD package naming convention changes

- .github/workflows/nightly.yml
- .github/workflows/pr_test.yml
- .rubocop.yml
- .travis.yml
- metadata.json
(MAINT) PDK update for GHA workflows + Litmus updates
pdk version: `1.18.1`
> pdksync - (MAINT) PDK update for GHA workflows + Litmus updates

- manifests/vhost.pp
Given the relatively close time of the `v6.0.0` release after the
`$use_servername_for_filenames` introduction, and the fact that it is
slated to change it's default value and behaviour from the next major
release, we are adjusting the timeline to give more people time to
adjust.
> (MAINT) Adjust $use_servername_for_filenames behaviour change timeline

- manifests/mod/dav_svn.pp
- spec/acceptance/mod_dav_svn_spec.rb
- spec/classes/mod/dav_svn_spec.rb
As far as I can tell Debian 10 still needs this work-around.
> Fix dav_svn for Debian 10

- manifests/default_mods.pp
- manifests/init.pp
- manifests/mod/fastcgi.pp
- manifests/mod/proxy_html.pp
- manifests/params.pp
- manifests/version.pp
- spec/spec_helper_local.rb
CentOS 8 stream doesn't have a minor version so this check likely fails. However, it's irrelevant here and we can use the major release version fact instead.
There are a lot more odd cases with facts, but I don't want to touch too much code.
> Compare with major release version

- templates/mod/autoindex.conf.erb
The original intent of HEADER* and README* in the IndexIgnore was
probably to ignore the files that are included at the top (HeaderName) and
bottom (ReadmeName) of the index listing. But the wildcard will hide other
files, like README.txt, so use full filenames instead.
> Fix HEADER* and README* wildcards in IndexIgnore

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
in the apache documentation https://httpd.apache.org/docs/2.4/fr/mod/core.html#servername
```Syntax:	ServerName [scheme://]domain-name|ip-address[:port]```
add support for this syntax when use_servername_for_filenames is set to true.
> support for uri for severname with use_servername_for_filenames

- REFERENCE.md
- manifests/mod/security.pp
- manifests/params.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
- templates/mod/security_custom.conf.erb
Basic Info
Module Version: 6.0.0
Puppet Version: 6.21.1
OS Name/Version: RHEL
Apache module activates the mod_security, but there is no way to manage custom rules.
For example, to override rules or create rules, etc.
Desired Behavior:
Allow adding custom rules to the security configuration.
Actual Behavior:
Functionality does not exist.
> (MODULES-11061) mod_security custom rule functionality

- manifests/vhost.pp
- spec/acceptance/apache_ssl_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_ssl.erb
* Allow ssl_honorcipherorder on apache::vhost to take booleans as every other on/off parameter does.
* Default to not outputting SSLHonorCipherOrder at all, as before.
* Also accept on/off to maintain backwards compatibility. (Note, the code would previously accept any value and output it verbatim. But since Apache will only accept on/off, I don't think it's necessary to maintain *that* level of backwards-compatibility).
* Add tests for the new functionality as well as backwards compatibility - this need scrutiny as I have not written rspec tests before.
(fixes MODULES-11068)
> (MODULES-11068) Allow apache::vhost ssl_honorcipherorder to take boolean parameter

- .github/workflows/auto_release.yml
- Rakefile
- metadata.json
- spec/spec_helper.rb
(maint) PDKSync - PDK Update
pdk version: `2.1.0`
> pdksync - (maint) PDKSync - PDK Update

- manifests/mod/disk_cache.pp
- spec/classes/mod/disk_cache_spec.rb
- templates/mod/disk_cache.conf.erb
Need more control over the default behaviour. Causes issue when only a particular path is to be cached and not the whole website.
> The default disk_cache.conf.erb caches everything. 

- manifests/mod/passenger.pp
- manifests/version.pp
- updated `$default` variable for Amazon Linux 2
The default `httpd` package version on the Amazon Linux 2 is `2.4`
```
Name        : httpd
Arch        : x86_64
Version     : 2.4.46
Release     : 1.amzn2
Size        : 1.3 M
Repo        : amzn2-core/2/x86_64
Summary     : Apache HTTP Server
URL         : https://httpd.apache.org/
License     : ASL 2.0
Description : The Apache HTTP Server is a powerful, efficient, and extensible
: web server.
```
Based on the above we need to update the `$default` variable to support AL2
> Update the default version of Apache for Amazon Linux 2

- manifests/vhost.pp
The warning about $use_servername_for_filenames is long and may not affect users. If they use a normal $name, there would effectively be no difference. This compares $name to $normalized_servername. The warning is only relevant Only if they differ.
Technically there could be a space in $servername (since there is no data type to enforce validation) but Apache wouldn't accept that anyway.
It also fixes two typos in the warnings.
Please make sure my logic is correct here, I'm not 100% sure it is.
> Only warn about servername logging if relevant

- CHANGELOG.md
- REFERENCE.md
- metadata.json
Manual release due to issues with auto-release job
> Release version 6.3.0

- manifests/mod/php.pp
- spec/classes/mod/php_spec.rb
Request for a review
The configuration file is updated in the required format for php_version 8 (/etc/httpd/conf.modules.d/php.load)
` LoadModule php_module modules/libphp.so`
Unit tests are updated to reflect the change.
> (MODULES-10899) Load php module with the right libphp file

- REFERENCE.md
- manifests/vhost.pp
With this empty line between the commend and the define, puppet-strings doesn't consider the comment as a documentation string. That means all the documentation that is written doesn't show up in REFERENCE.md.
I can't regenerate REFERENCE.md due to a missing puppet-module-posix-default-r3.0 gem so somebody else has to do that.
It was found in https://github.com/puppetlabs/puppetlabs-apache/pull/2157/files#r663838497 and introduced in 7e233fe7cc108605384506f11083aeea6e3a2464.
> (maint) Fix puppet-strings docs on apache::vhost

- REFERENCE.md
- manifests/mod/userdir.pp
- spec/classes/mod/userdir_spec.rb
- templates/mod/userdir.conf.erb
`UserDir` can be various forms of strings (see
https://httpd.apache.org/docs/2.4/howto/public_html.html) whereas
`Directory` must be an absolute path. This allows UserDir to be
specified separately.
The unit test showing multiple values for `$path` seems to be incorrect
according to https://httpd.apache.org/docs/2.4/mod/core.html#directory
> Allow custom userdir directives

- manifests/params.pp
This change updates the version handling to better future proof the
logic when newer versions are shipped. This should prevent having to add
things like #2063, #2021, #2038, etc.
> (MODULES-11075) Improve future version handling for RHEL

- REFERENCE.md
- manifests/init.pp
- manifests/mod/ssl.pp
- manifests/mod/ssl/reload.pp
- manifests/params.pp
- manifests/vhost.pp
- spec/acceptance/apache_ssl_spec.rb
- spec/classes/mod/ssl_spec.rb
- spec/defines/vhost_spec.rb
- spec/spec_helper_acceptance_local.rb
This fixes issue MODULES-10847, which we also wanted to solve.
The solution with those helper files seems a bit odd, but the original ssl files could be managed by any means outside of the apache module or even outside of puppet, so this was the only way i could image to achieve it.
(Slightly offtopic: Let me add that this module gave me a love/hate relationship with spec/acceptance tests. First i blamed wrong tests to be the cause for failing, but in the end it was my own stupid code. Finally i could manage getting tests run green at my desktop - hope they will do in the modules CI setup as well.)
> Add feature to reload apache service when content of ssl files has changed

- manifests/params.pp
- spec/classes/mod/php_spec.rb
tl;dr `$::operatingsystemrelease` is different from
`$::operatingsystemmajrelease`. `$::operatingsystemmajrelease` returns
'11.0' on Debian 11, whereas `$::operatingsystemmajrelease` is `11`.
In addition `versioncmp()` says that `'11.0'` is greater than `11`.
Without this change, the module sets the default PHP version on Debian
11 to 7.2, but the actual default in Debian is 7.4:
* https://packages.debian.org/bullseye/php
The 7.2 currently comes from the default entry in the selector
statement:
* https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/params.pp#L401
To test:
```puppet
notify { "operatingsystemrelease compared to 11: ${versioncmp($::operatingsystemrelease, '11')}":}
notify { "operatingsystemmajrelease compared to 11: ${versioncmp($::operatingsystemmajrelease, …
```
> Debian 11: fix typo in `versioncmp()` / set default php to 7.4

- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/default_mods_spec.rb
- spec/acceptance/itk_spec.rb
- spec/acceptance/prefork_worker_spec.rb
- spec/acceptance/vhost_spec.rb
Opened PR to enable the tests.
The tests are passing from the latest release of specinfra supports service testing commands on all OS
> (FM-8483) reenable the testcases

- REFERENCE.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_docroot.erb
DocumentRoot is used for other directives when a Virtual Document Root is not found.  
For backwards compatibility, `docroot` is still ignored unless you set the `virtual_use_default_docroot` to `true`.
For example, to show a custom 404 message, you might use mod_rewrite, but that needs a `DocumentRoot` to be set:
```
#
<VirtualHost *:80>
ServerName projects.example.com
VirtualDocumentRoot "/var/www/projects/_webroots/%0"
DocumentRoot "/var/www/projects/_webroots"
<Directory "/fs/www/projects">
Options FollowSymLinks MultiViews Indexes
AllowOverride None
Require all granted
</Directory>
ErrorLog "/var/log/httpd/projects.cs.umd.edu_error.log"
RewriteEngine On
#Show errors for missing sites
RewriteCond %{HTTP_HOST} "^([^:/]*)(:.+)?" [NC]
RewriteCond '/var/www/projects/_webroots/%1' !-d …
```
> Allow `docroot` with `mod_vhost_alias` `virtual_docroot`

- REFERENCE.md
- manifests/vhost.pp
For the main virtual host configuration, there is a parameter `override` for this: https://forge.puppet.com/modules/puppetlabs/apache/reference#override
However in the directories parameter, it needs to be set to `allow_override`.
It is confusing to have two different names for the same thing, but changing it at this point would probably break people's settings. At least we can document its usage in the example.
> Show `allow_override` key in docs.

- README.md
(MODULES-10646) - README link fixes
Checked each link and fixed ones that didn't resolve and removed deprecated ones not referenced in the README. For the majority of them they weren't resolving because the **Reference** section was moved to a separate file REFERENCE.md. However, because the reference section in the repo [https://forge.puppet.com/]() seems to be a folder, not a file, relative references won't work. I opted to point the links to the references as absolute URLs to the repository on [https://forge.puppet.com/modules/puppetlabs/apache/reference]().
> (Modules-10646) - README link fixes

- manifests/init.pp
- spec/spec_helper_acceptance_local.rb
It was dropped in https://github.com/gentoo/gentoo/commit/872597ae0890e11ac15718f655935f1b0c9e0dbd.
Also sets the Apache version to 2.4 in FreeBSD acceptance. See invidivual commits for details.
> Drop Apache 2.2 support with Gentoo

- .github/workflows/spec.yml
- README.md
- manifests/mod/fastcgi.pp
- manifests/mod/security.pp
- manifests/mpm.pp
- manifests/params.pp
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/php_spec.rb
- spec/spec_helper_acceptance_local.rb
- spec/util/apache_mod_platform_compatibility_spec.rb
Unsure of whether this should be merged now as the last release backwards incompatible and this will make two in a row.
In the event that it is we should ensure that as many of the community prs are brought into it as possible.
> (GH-iac-334) Remove code specific to unsupported OSs

- manifests/mpm.pp
This takes the approach of listing the disabling steps once rather than repeating it for every mpm.
I wasn't quite sure on the prefork disabling. Does prefork need to stay enabled for itk?
> Restructure MPM disabling

- manifests/mod/proxy_connect.pp
- spec/classes/mod/proxy_connect_spec.rb
It's safe to assume the version is >= 2.2 so the conditional can be dropped.
> Drop Apache 2.0 compatibility code

- manifests/mod/passenger.pp
- manifests/vhost.pp
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/passenger_spec.rb
- spec/defines/vhost_spec.rb
- templates/mod/passenger.conf.erb
- templates/vhost/_directories.erb
- templates/vhost/_passenger.erb
The latest passenger include a new option to load ruby bundles earlier,
working around deployment issues.  See:
* https://github.com/phusion/passenger/issues/2410
* https://github.com/phusion/passenger/issues/2409
> Add support for PassengerPreloadBundler

- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
In 7e233fe7cc108605384506f11083aeea6e3a2464 a plan was made to change the naming. In 6b2a20a390df597f04222571dc7fac366a8ea898 it was already from 6.0.0 to 7.0.0. Now that 7.0.0 has been released, the default isn't going to change. This time I'm suggestion to drop the plan altogether and stop bothering users with this.
> Remove warnings and plans to change vhost default naming

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_gssapi.epp
This adds support for the `GssapiBasicAuth` setting
which allows to fall back to basic auth if `NEGOTIATE` fails.
> mod_auth_gssapi: Add support for `GssapiBasicAuth`.

- manifests/version.pp
- spec/classes/apache_spec.rb
- spec/classes/mod/wsgi_spec.rb
- spec/spec_helper_local.rb
The goal of this PR is to simplify Fedora handling. By now it can be assumed every Fedora is on Apache 2.4 and most users can be expected to run on Red Hat. Fedora isn't formally in metadata.json so this is best effort anyway. Users do not lose anything by this change, but for developers there is less code to maintain.
> Drop support for Fedora < 18

- manifests/vhost/custom.pp
- manifests/vhost/fragment.pp
- manifests/vhost/proxy.pp
- spec/defines/vhost_proxy_spec.rb
- types/vhost/proxypass.pp
This builds on apache::vhost::fragment with a more specialized type for
a reverse proxy setup. This reuses the same template as apache::vhost
but has data types. The types are stricter, but this leads to a clearer
API. For example, it doesn't accept String and Array[String] but in that
case always wants an Array.
The old parameters on vhost remain and can continue to be used.
> Add an apache::vhost::proxy define

- spec/acceptance/mod_authnz_ldap_spec.rb
- spec/spec_helper_acceptance_local.rb
Migrates from stahnma/epel to puppet/epel (after it was transferred) and also stops using EPEL 7 on EL8. That is unlikely to work and can easily breaking things. Perhaps it's why the EL8 tests are often timing out in CI.
> Acceptance tests: correct EPEL usage

- manifests/vhost.pp
- spec/acceptance/default_mods_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_aliases.erb
This also implements a real test on the rendered template. It appears it was passing in something invalid ever since it was introduced in f1d64a0a0b71af0102d10da69e333aa9ac5a15f5.
> Use a stricter data type on apache::vhost::aliases

- spec/defines/vhost_spec.rb
This uses chaining to remove a lot of separate expectations. The big benefit is that it's a lot quicker to run and if one thing fails (like the whole catalog fails to compile) there is just a single error for the fragment rather than one for each test. It's also a lot shorter.
I'm submitting this as a separate PR so I'm testing on a clean slate. I do want this in https://github.com/puppetlabs/puppetlabs-apache/pull/2255 because it makes moving things easier.
> Group assertions in vhost spec

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
See invididual commits for details. This doesn't modify any code, it's just tests and docs.
> Correct vhost parameter documentation and run vhost tests on all supported OSes

- manifests/default_mods.pp
- manifests/mod/authz_groupfile.pp
- manifests/mod/proxy_ajp.pp
- manifests/mod/proxy_balancer.pp
- manifests/mod/proxy_connect.pp
- manifests/mod/proxy_fcgi.pp
- manifests/mod/proxy_html.pp
- manifests/mod/proxy_http.pp
- manifests/mod/proxy_wstunnel.pp
- manifests/vhost.pp
- spec/acceptance/default_mods_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/classes/mod/authz_groupfile_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
The data passed to the directories parameter of apache::vhost often implies a module should be present. This change inspects the passed data and automatically includes modules if needed. This makes it easier to use via Hiera while disabling all default mods.
Because of this change one acceptance test becomes obsolete: it no longer fails and just works.
To make this easier the data type is simplified. This means users need to be a bit stricter about their input, but they need to worry less about including the right modules.
This replaces https://github.com/puppetlabs/puppetlabs-apache/pull/2250.
> Automatically include modules used in vhost directories

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_gssapi.epp
Adding config items:
- allowedmech
- authname
- authtype
- basicauth
> Allow additional settings for GSSAPI in Vhost

- spec/defines/vhost_spec.rb
Defining variables in rspec is dangerous since they end up being defined on classes. That means that in a for loop it may end up being defined as the last running version. A let block provides proper variable scoping.
This wasn't a problem until fb0d0782d8221741474f8170dacf522f6ce32b69 where it ran spec tests on all operating systems. Then it became dependent on the order of the supported operating systems.
Fixes: fb0d0782d8221741474f8170dacf522f6ce32b69
> Define apache_name via a let block

- manifests/vhost.pp
- manifests/vhost/custom.pp
- manifests/vhost/fragment.pp
- manifests/vhost/proxy.pp
- spec/type_aliases/vhost_priority_spec.rb
- types/vhost/priority.pp
In f41251e336fa3e7c31c19968ccee74121cf71e47 the type was narrowed to no longer allow strings, but this can cause problems.
Sorting is alphabetical and you need to format it for the correct sorting. So to make sure 2 loads before 10 you need to format it as 02.  While the vhost can do some printf style magic to change 2 to 02, it must then also know what the highest number is. Otherwise 100 is sorted before 20. By allowing strings, you allow the caller to fix this.
A type alias is introduced to reduce duplication and make it easier to track.
Fixes: f41251e336fa3e7c31c19968ccee74121cf71e47
> Allow vhosts to have a string priority again

- manifests/mod/php.pp
- manifests/params.pp
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/php_spec.rb
EL 9 doesn't ship mod_php, so this is uninstallable. By making it a required parameter (which effectively was already the case) and setting the version to undef the catalog fails to compile by default. This still allows users to set it if they build a mod_php somehow.
EL 9 users should use php-fpm instead.
A draft right now to see which tests fail.
Fixes: edbdb65b06418779aa30ebe6cf0948007cc51a29
> Disable mod_php on EL9

- manifests/default_mods.pp
Pull-Request #2252 breaks the usage of auth_basic in a vhost, because the module is
declared twice:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Apache::Mod[auth_basic] is already declared at (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/default_mods.pp, line: 142); cannot redeclare (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/mod/auth_basic.pp, line: 7) (file: /etc/puppetlabs/code/environments/module_updates/modules/apache/manifests/mod/auth_basic.pp, line: 7, column: 3) (file: …
> fix duplicate definition of auth_basic-mod

- manifests/custom_config.pp
cc: @ekohl 
Same reason as c11ab1fdce6ab11cbcb1d55deadf1531191c9e35 for vhosts - reusing Apache::Vhost::Priority data type.
In f41251e the type was narrowed to no
longer allow strings, but this can cause problems.
Sorting is alphabetical and you need to format it for the correct
sorting. So to make sure 2 loads before 10 you need to format it as 02.
While the custom_config can do some printf style magic to change 2 to 02, it
must then also know what the highest number is. Otherwise 100 is sorted
before 20. By allowing strings, you allow the caller to fix this.
A type alias is introduced to reduce duplication and make it easier to
track.
Fixes: f41251e
> Allow custom_config to have a string priority again

- manifests/params.pp
- spec/classes/mod/auth_kerb_spec.rb
- spec/spec_helper_local.rb
libapache2-mod-auth-kerb is unavailable in Debian Bullseye[1]
libapache2-mod-auth-kerb was removed in Debian Buster[2]
[1]: https://packages.debian.org/buster/libapache2-mod-auth-kerb
[2]: https://packages.debian.org/stretch/libapache2-mod-nss
> Remove auth_kerb and nss from Debian Bullseye

- manifests/mod/auth_basic.pp
- manifests/mod/auth_cas.pp
- manifests/mod/auth_mellon.pp
- manifests/mod/auth_openidc.pp
- manifests/vhost.pp
- spec/acceptance/auth_openidc_spec.rb
- spec/classes/mod/auth_cas_spec.rb
- spec/classes/mod/auth_gssapi_spec.rb
- spec/classes/mod/auth_kerb_spec.rb
- spec/classes/mod/auth_mellon_spec.rb
- spec/classes/mod/auth_openidc_spec.rb
On EL 8 mod_auth_openidc is in a DNF module that must be enabled. Otherwise the package is uninstallable. This is verified by adding an acceptance test for the class.
The inheritance on apache::params is removed since it was redundant. That is only needed if a class parameter uses apache::params.
$oidc_settings on apache::vhost is changed to have a default. The template expects one and With that it's impossible to miscompile. The alternative is to implement a fail() inside the code if it is empty, but this provides some safety.
> Manage DNF module for mod_auth_openidc

- manifests/mod/alias.pp
- spec/classes/mod/alias_spec.rb
with the commit f41251e336fa3e7c31c19968ccee74121cf71e47, icons_path set to false does not work.
This commit fixes that.
> Allow setting icons_path to false so no alias will be set for it

- manifests/mod/php.pp
- manifests/params.pp
- metadata.json
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/php_spec.rb
(GH-cat-11) Certify Support for Ubuntu 22.04
pdk version: `2.4.0`
> pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04

- templates/vhost/_require.erb
If we take the expression:
```ruby
!(_item['require'] && _item['require'] != '') && _item['require'] !~ /unmanaged/i && !(_item['auth_require'])
```
This is hard to read, but equal to:
```ruby
(!_item['require'] || _item['require'] == '') && _item['require'] !~ /unmanaged/i && !(_item['auth_require'])
```
This makes it easier to see that item must be `nil` or `''`. Those will never match `/unmanaged/i` so it can be simplified to:
```ruby
(!_item['require'] || _item['require'] == '') && !(_item['auth_require'])
```
Just before it is a block that already checks the last section, so it can be reduced to an elsif on that block.
> Simplify the logic in _require.erb

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
There are cases where you want to exclusively inherit RewriteRules from e.g. global scope without specifying vHost-specific rewrites - which is now allowed again.
> Allow RewriteInherit with empty rewrites

- manifests/init.pp
Additional variable added at request of community to allow for `vhost_enable_dir` to be disabled on Debian systems.
Due to the way in which aid variable inherits from the params manifest, simply setting it to `undef` does not work as when this is done it's logic assumes it should inherit from the default params value.
> (maint) Add variable manage_vhost_enable_dir

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
> (MAINT) Removing support for CentOS 8

- manifests/custom_config.pp
- manifests/init.pp
- manifests/mpm/disable_mpm_event.pp
- manifests/mpm/disable_mpm_prefork.pp
- manifests/mpm/disable_mpm_worker.pp
- manifests/params.pp
- spec/defines/custom_config_spec.rb
Changes made to ensure that no malformed commands are passed through to the system.
Includes an update the the $verify_command variable type
The unless variable in an exec manifest, which $verify_command is directly passed too, accepts either an Array or and Array of Arrays as input.
Updating the variables type and default values to match this.
In the case where it is passed a String it proceeds to wrap it in an Array and then treat it as such.
> (maint) Codebase Hardening

- spec/acceptance/vhost_spec.rb
- templates/vhost/_directories.erb
puppetlabs-apache 6.5.1 with `options => false`
```
<Directory "/var/www/html/myapp">
AllowOverride None
Require all granted
</Directory>
```
puppetlabs-apache latest with `options => []`
```
<Directory "/var/www/html/myapp">
Options
AllowOverride None
Require all granted
</Directory>
```
> fix directory empty options if an empty array is being used

- lib/facter/apache_version.rb
- spec/unit/facter/util/fact_apache_version_spec.rb
Prior to this commit, this module contained instances of Facter::Util::Resolution.exec and Facter::Util::Resolution.which, which are deprecated. This commit aims to replace these exec helpers with their supported Facter::Core::Execution counterparts.
This commit:
- Replaced all Facter::Util::Resolution instances with corresponding Facter::Core::Execution exec helpers
> (CONT-173) - Updating deprecated facter instances

- manifests/init.pp
- spec/classes/apache_spec.rb
- templates/httpd.conf.erb
Since fc6cced03e60c5a78bceb006dd4267fc37f54959 the parameter no longer ends up in the main configuration. It was still used in apache::mod::shib until 049fd54b57e8a4f28ceeea4888456eafe1509fa1. Since then it's been unused.
This changes it to an optional non-empty string which means it doesn't change the default config, but still allows users to set the ServerAdmin in the main Apache config.
> Make serveradmin an optional parameter and use it

- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
While it is a parameter for apache::vhost, this allows setting it server wide just like SSLCipherSuite.
> Support setting SSLProxyCipherSuite on mod_ssl

- manifests/init.pp
- manifests/vhost.pp
Following https://httpd.apache.org/docs/current/howto/http2.html the first step is to load the http2 module. By inspecting the protocols argument users can enable HTTP/2 via Hiera.
> Automatically enable mod_http2 if needed

- spec/setup_acceptance_node.pp
- spec/spec_helper_acceptance_local.rb
This makes it easier to maintain. You get proper syntax highlighting in your editor and can even lint it. This also converts some shell lines to pure Puppet. This reduces the need for large local spec_helper_acceptance modifications. The pattern is copied from voxpupuli-acceptance where the beaker setup automatically detects if the file is present and applies it.
It does drop EL6 EPEL support, following 4922544709313e0b7d176013e6f8118b85fdf96a.
> Extract acceptance node setup to a separate file

- manifests/mod/php.pp
- spec/classes/mod/php_spec.rb
Fixes loading correct libphp file when RedHat AND PHP 8.
Fixes #2332
> Fix RedHat + PHP 8 libphp file

- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/setup_acceptance_node.pp
This attempts to unify SELinux handling in the tests. It moves the package installation to the acceptance spec helper to reduce duplication. It then makes the set_apache_defaults line idempotent and restorecon_apache correctly chained. This works around [PUP-10548] which is that Puppet doesn't reload file contexts within a run. That means it must first create the file(s) and then run restorecon to get correct contexts.
[PUP-10548]: https://tickets.puppetlabs.com/browse/PUP-10548
> Clean up SELinux handling in acceptance testing.

- manifests/init.pp
- spec/acceptance/apache_parameters_spec.rb
- templates/httpd.conf.erb
Adds optional parameter for setting the limit on the allowed size of a client's HTTP request-line
New PR reopened for closed PR https://github.com/puppetlabs/puppetlabs-apache/pull/2208
Added parameter definition and code for testing
> add LimitRequestLine parameter

- manifests/mod/security.pp
- spec/classes/mod/security_spec.rb
The unique_id module gets installed/loaded with its internal id 'unique_id_module' used as name; resulting in inconsistent naming and possible double entries if the module was already enabled outside of puppet (or security.pp).
> remove _module from apache::mod::unique_id name.

- manifests/mpm/disable_mpm_event.pp
- spec/classes/apache_spec.rb
there were a few things broken:
* a2dismod was called with the wrong module name. at least on apache 2.4.54 on Debian 11 it is named mpm_event, not event
* the paths to the files were wrong
* a2dismod already purges the .load and .conf file, the exec resources
are not required (even then a file resource would probably be cleaner
to purge them)
* Apache needs to be reloaded, so just running this priot to
apache2::service isn't enough, it needs to be a notify
This initially worked but was changed from mpm_event to event in https://github.com/puppetlabs/puppetlabs-apache/pull/1961. Then it was fixed in https://github.com/puppetlabs/puppetlabs-apache/pull/2034 by adding the exec resources, but the actual a2dismod was still broken.
> disable::mpm_event: Fix module deactivation

- manifests/params.pp
- spec/classes/mod/proxy_html_spec.rb
Previously trying to activate mod_proxy_html on FreeBSD resulted in the following error:
```
Error: /Stage[main]/Apache::Mod::Proxy_html/Apache::Mod[proxy_html]/Package[www/mod_proxy_html]/ensure: change from 'absent' to 'present' failed:
Execution of '/usr/local/sbin/pkg install -qy www/mod_proxy_html' returned 1:
pkg: No packages available to install matching 'www/mod_proxy_html' have been found in the repositories
```
The module files are already included in the base Apache port/package, the separate port was EOLed in 2018:
https://www.freshports.org/www/mod_proxy_html
> fix mod_proxy_html on FreeBSD

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy.erb
It's a valid usecase to set ProxyAddHeaders to Off. That's currently only possible when other proxy settings are configured as well. It needs to be independant.
> vhost: Make ProxyAddHeaders configureable

- README.md
Prior to this commit the old team was being referenced.
This commit brings the documentation in line with the team that now supports it.
> (MAINT) Replace IAC Team with CAT Team

- templates/mod/ext_filter.conf.erb
- templates/vhost/_directories.erb
- templates/vhost/_proxy.erb
- templates/vhost/_wsgi.erb
See individual commits for details. Note I haven't tested this and will rely on CI and review to spot errors.
> Simplify templates by reusing methods

- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
- templates/mod/security_crs.conf.erb
https://github.com/puppetlabs/puppetlabs-apache/commit/175d6d4e513f632bce60b7a07b9ec199b5ee4fbd broke the template.
~~This commit switches back to the old syntax.~~
This commit switches to proper structured facts.
Contains the same changes as https://github.com/puppetlabs/puppetlabs-apache/pull/2372 to validate it works now properly.
>  security{,_crs}.conf: switch to structured facts

- spec/classes/mod/security_spec.rb
This os a test to validate that https://github.com/puppetlabs/puppetlabs-apache/commit/175d6d4e513f632bce60b7a07b9ec199b5ee4fbd broke the template on Debian.
> (#2371) security.conf: Test for SecTmpDir

- manifests/params.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.erb
- templates/mod/security_crs.conf.erb
This fixes https://github.com/puppetlabs/puppetlabs-apache/issues/2374. The issue was discovered in https://github.com/puppetlabs/puppetlabs-apache/pull/2373 while fixing https://github.com/puppetlabs/puppetlabs-apache/issues/2371.
> (#2374) Suse: Switch modsec_default_rules to array 

- spec/classes/mod/security_spec.rb
- templates/mod/security_crs.conf.erb
OS Family comparison should be against `RedHat` not `Redhat`
> (BugFix) Update OS Family comparison to correctly match

- manifests/default_mods.pp
- manifests/mod/version.pp
re adding mod_version which was accidentally removed with the drop of "apache 2.2 Support" in #2329.
> Adding mod_version module to be activated by default

- templates/vhost/_directories.erb
It's valid for a DocumentRoot to be missing (`docroot => false`).
However, in the directories section, this leads to a confusing message:
`## Directories, there should at least be a declaration for false`
> Suppress bad Directory comment when DocumentRoot is not set

- manifests/default_confd_files.pp
- manifests/default_mods.pp
- manifests/init.pp
- manifests/mod.pp
- manifests/mod/cgid.pp
- manifests/mod/dav_fs.pp
- manifests/mod/disk_cache.pp
- manifests/mod/event.pp
- manifests/mod/itk.pp
- manifests/mod/peruser.pp
- manifests/mod/prefork.pp
- manifests/mod/ssl.pp
- manifests/mod/version.pp
- manifests/mod/worker.pp
- manifests/mpm.pp
Ensuring that the correct values are compared against facter, there seem to be many cases where lowercase has been used in place of uppercase.
> (BUGFIX) Update to ensure correct facter comparisons

- REFERENCE.md
- manifests/mod/proxy.pp
- templates/mod/proxy.conf.erb
apache::mod::proxy allowed Stdlib::IP::Address as a class parameter, but proxy.conf.erb assumed it was an array.
> Fixes mod::proxy allow_from parameter inconsistency #2352

- REFERENCE.md
- manifests/vhost.pp
The `php_values` parameter requires a Hash, but gives examples from the ~v7 era when other values were allowed.
> Fix example code for apache::vhost::php_values

- spec/defines/vhost_spec.rb
- templates/vhost/_rewrite.erb
In 7b22dae the default value for $rewrites was changed from undef to [] in manifests/vhost.pp. This results in templates_vhost/_rewrite.erb always evaluating to false (boolean check on an empty array variable is still true) unless $rewrites is explicitly set to undef. This results in the content of $rewrite_rule being ignored.
closes: #2318
> fix rewrite rules being ignored

- manifests/custom_config.pp
Allow Sensitive type in addition to String type for apache::custom_config::content
> #2391 Allow Sensitive type in addition to String type

- CHANGELOG.md
- metadata.json
Minor release before merging the Puppet 8 major update.
> Release prep Apache v9.1.3

- manifests/mod.pp
- manifests/mod/jk.pp
- manifests/mod/php.pp
In the next puppetlabs-stdlib major version this function will be dropped. Native Puppet is used instead.
https://github.com/puppetlabs/puppetlabs-stdlib/pull/1319 broke this
> Remove has_key usage

- manifests/mod/proxy_http2.pp
- manifests/vhost.pp
- manifests/vhost/proxy.pp
- spec/classes/mod/proxy_http2_spec.rb
- spec/classes/mod/proxy_http_spec.rb
- spec/defines/vhost_proxy_spec.rb
Currently untested, but having a PR makes it easier to consume in my test environment.
Fixes #2264
> Add mod_proxy_http2 support

- manifests/mod/php.pp
- spec/setup_acceptance_node.pp
Enable legacy SP3 repo so that we can leverage the old packages without any issues.
New release of SUSE 15 introduced new version SP4 which deprecated old packages where `apache2-mod_php7` is one of them. As the package is deprecated with SP4 repo so user will not able to install.
Due to package got deprecated from new repo, respective package manager is not able to install.
> (MAINT) Enable legacy SP3 repository for SUSE

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Add MellonSetEnv support, will prepend MELLON_ to the environment variable name
Fixes #2416
> Add MellonSetEnv support

- manifests/mod/php.pp
- spec/setup_acceptance_node.pp
Enable legacy SP5 repo so that we can leverage the old packages without any issues.
New release of SUSE introduced new version SP5 which deprecated old apache2-mod_php7 package. As the package is deprecated with old SP4 repo so user will not able to install.
Due to package got deprecated from new repo, respective package manager is not able to install. This also affects the modules that is using java internally as a dependency or to install packages.
> (CAT-1261)-update_SUSE_repo_name

- README.md
- manifests/mod/ssl.pp
- manifests/vhost.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
- templates/vhost/_ssl.erb
Adding support for enable user to pass the different ciphers for different protocols.
- https://github.com/puppetlabs/puppetlabs-apache/issues/2422
- N/A
> (CAT-1281) - Support to add cipher with respective ssl protocol

- manifests/default_mods.pp
- manifests/mod/log_forensic.pp
- spec/classes/mod/log_forensic_spec.rb
Adding support for `log_forensic` module with apache.
- https://github.com/puppetlabs/puppetlabs-apache/issues/2260
- https://github.com/puppetlabs/puppetlabs-apache/issues/2260
> (CAT-1283) - Enable forensic module

- manifests/mod/remoteip.pp
- templates/mod/remoteip.conf.epp
The type Stdlib::Host includes Stdlib::IP::Address, so the variant is redundant. There's also no way to pass nested arrays so flatten is not needed.
> Simplify data types and array handling

- REFERENCE.md
- manifests/default_mods.pp
- manifests/init.pp
- Making mod list more restrictive.
- Improving the documentation for `default_mods` overriding with custom mods.
N/A
> (CAT-1308) Making mod list more restrictive and minor improvements in documentation for default mods override

- spec/type_aliases/loglevel_spec.rb
- types/loglevel.pp
Apache::LogLevel allows invalid strings like 'warning' which are not accepted by apache httpd
> strickter loglevel syntax verification

- .rubocop_todo.yml
- README.md
- REFERENCE.md
- lib/puppet/functions/apache/authz_core_config.rb
- manifests/default_mods.pp
- manifests/mod/authz_core.pp
- manifests/vhost.pp
- spec/functions/authz_core_config_spec.rb
- templates/vhost/_authz_core.epp
- templates/vhost/_directories.erb
- Adding support for Authz_core module nested require statement.
- Regenerating REFERENCE.md 
https://github.com/puppetlabs/puppetlabs-apache/issues/2315
https://github.com/puppetlabs/puppetlabs-apache/issues/2315
> (CAT-1417) Nested require support for authz_core mod

- spec/acceptance/itk_spec.rb
- spec/classes/mod/lbmethod_bybusyness.rb
- spec/classes/mod/lbmethod_byrequests.rb
- spec/classes/mod/lbmethod_bytraffic.rb
- spec/classes/mod/lbmethod_heartbeat.rb
- spec/defines/vhost_spec.rb
- spec/util/apache_mod_platform_compatibility_spec.rb
With the removal of support for RHEL6 from our modules, work must be done to cleanup and remove any residual code.
This PR does the same for Apache repo module. More info can be found #2326
> (CAT-1424)-Removal of redhat/scientific/oraclelinux 6 for apache module

- REFERENCE.md
Regenerating REFERENCE.md.
N/A
> (MAINT) - Updating REFERENCE.md

- REFERENCE.md
- manifests/init.pp
- manifests/mod/passenger.pp
- manifests/vhost.pp
- spec/acceptance/vhost_spec.rb
- spec/classes/mod/passenger_spec.rb
- spec/defines/vhost_spec.rb
- templates/mod/passenger.conf.epp
- templates/vhost/_scriptalias.erb
Cleanup for deprecated content : 
- scriptaliases parameter
- passanger params
Thanks @ekohl for pointing out the deprecated content and raising the bar for apache module.
Also thanks https://github.com/puppetlabs/puppetlabs-apache/pull/2469 which I used it to fix scriptaliases spec fixes.
> (CAT-1449) - Remove deprecated parameters for scriptaliases & passenger

- REFERENCE.md
- manifests/mod/passenger.pp
- manifests/vhost.pp
- spec/classes/mod/passenger_spec.rb
- templates/mod/passenger.conf.epp
Added new parameters for passenger mod.
N/A
> (CAT-1450) - Added new parameters for passenger mod

- templates/mod/ssl.conf.epp
While converting ERB to EPP the nil check evaluation got missed, so fixing the same.
Have taken this opportunity to check other recently converted files and haven't seen discrepancy, seems the above was miss. 
Issue - https://github.com/puppetlabs/puppetlabs-apache/issues/2472
> (CAT-1451) - Fixing nil check fix for SSL config

- README.md
- spec/util/_resources/test_metadata_json.rb
> Update issue link in ReadMe and metadata

- REFERENCE.md
- manifests/mod/apreq2.pp
- manifests/mod/md.pp
- manifests/mod/shib.pp
- manifests/params.pp
- spec/acceptance/vhost_spec.rb
- spec/classes/mod/php_spec.rb
- spec/classes/mod/security_spec.rb
Debian 9 was already removed from metadata.json and isn't supported anymore. This PR drops some code leftovers.
> Drop EoL Debian 9 and older code

- REFERENCE.md
- manifests/mod/ssl.pp
Since Apache 2.2 was dropped, the value is always the same.
Fixes: cedd45b63be89ea54bd2a596e6cd3a3f60d4faf8 ("Drop Apache 2.2 support")
> Remove outdated parameter documentation for ssl_mutex

- REFERENCE.md
- manifests/mod/md.pp
- spec/classes/mod/php_spec.rb
- spec/classes/mod/security_spec.rb
- spec/defines/vhost_spec.rb
This deletes Ubuntu 16 and older code. Those versions are already gone from metadata.json.
> Drop EoL Ubuntu code

- templates/vhost/_directories.erb
`AllowOverrideList` allows more fine-grained control over which directives are allow in htaccess
There aren't any existing tests for `AllowOverride` and I am not sure where I would put new tests.
> Add AllowOverrideList support

- manifests/init.pp
This was probably added while refactoring templates to help diagnose
issues and should have been removed before the relevant PR was merged
but slip through.
This serve no purpose and only log useless information in the
puppetserver log so get rid of it.
> Remove useless notice

- REFERENCE.md
- manifests/vhost.pp
> vhost::directories: switch default from undef to empty array

- manifests/vhost.pp
- templates/vhost/_suexec.epp
The missing newline break apache configuration:
```
apache2: Syntax error on line 50 of /etc/apache2/apache2.conf: Syntax error on line 6 of /etc/apache2/sites-enabled/25-example.com-443.conf:6: <VirtualHost> was not closed.
```
Add the missing new line.
While here, also remove the legacy (now unused) template and fix
indentation of the generated statement.
This regression was introduced in 31a137bcb490e6a9041959e8f7115dceac91d4c0 which appear in no release so far.  So maybe we should label this `maintenance` rather than `bugfix`?
> Fix `mod_suexec` configuration

- templates/vhost/_file_header.epp
This slept through while converting templates form erb to epp.  Remove
it so that it is easier to spot regressions if the catalog is not
supposed to change but applying it in noop mode wants to change the
actual files.
> Fix extra newline at end of headers

- manifests/vhost.pp
This is missing a newline char and breaks on recent (12.0.0) puppetlabs-apache:
```
apache2: Syntax error on line 50 of /etc/apache2/apache2.conf: Syntax error on line 6 of /etc/apache2/sites-enabled/25-example.com-443.conf:6: <VirtualHost> was not closed.
```
This fix is inspired by fb9d1313, it's functionally the same. Adds the missing newline and also adds two spaces for indentation.
> Fix use_canonical_name directive

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
Allow customizing show_diff of vhost configuration file
A vhost configuration file may contain sensitive information. For example when mod_auth_openidc is used then the file may contain OIDCCryptoPassphrase. This introduces the parameter to allow users to hide diff when applying manifests, to avoid leaking secrets to outputs.
N/A
> vhost: Allow customizing show_diff

- manifests/mod/mime.pp
- manifests/params.pp
All [apache2 packages](https://packages.debian.org/bullseye/apache2) on Debian 10 and later already have a hard dependency on the `mime-support` package. While `mime-support` still exists on Debian 12 as a transitonal package, upcoming Debian 13 has removed it entirely.
This sets the `$mime_support_package` to undefined so that the package isn't managed on Debian, since it doesn't need to be.
Currently, the module fails completely on Debian testing (upcoming release 13 codenamed `trixie`):
```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install mime-support' returned 100: Reading package lists...                                                                          
Building dependency tree... …
```
> Stop managing mime support package on Debian

- spec/acceptance/vhost_spec.rb
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Two brackets have been added around the arguments of the second scope.call_function
The problem here is or was that the argument was not passed correctly to the function "authz_core_config" and you then got an error message from it that an incorrect variable type was passed.
"parameter 'config' expects a Hash value, got Tuple"
thanks to @hufschmidt for helping to find the error and solve the problem
For error reproduction it is sufficient to use "authz_core" in some way within a directory in a vhost.
For example as described in the ReadMe: https://github.com/puppetlabs/puppetlabs-apache/blob/b9ac34ca8a17c1bd507de01fc109d8fe73bf110c/manifests/vhost.pp#L1369-L1392
> Add missing brackets for function call

- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Support configuring the EnableSendfile option under Directory directives
The EnableSendfile option can be configured in a Directory directive to disable/enable the snedfile feature for specific paths as is described in https://httpd.apache.org/docs/2.4/en/mod/core.html#enablesendfile .
N/A
> Add EnableSendfile per directory

- manifests/mod/php.pp
- spec/setup_acceptance_node.pp
Updated code to use parameterised value for OS Major and Minor versions.
- The acceptance tests were failing for SLES-15 server
- Package "apache2-mod_php7" was not found on the SLES-15 server
- 'enable legacy repos' exec block was updated to fix the issue. ([link](https://github.com/puppetlabs/puppetlabs-apache/blob/main/manifests/mod/php.pp#L108-L117))
> Fix apache2-mod_php7 not found for SLES-15

- manifests/default_mods.pp
Include the systemd module for both AL2 and AL2023.
This resolves an issue where the service fails to start on AL2023.
https://github.com/puppetlabs/puppetlabs-apache/issues/2561
- [x ] Manually verified. (For example `puppet apply`)
> Include systemd module for Amazon Linux 2023

- REFERENCE.md
- types/oidcsettings.pp
#2569 / commit 90f7482290c4143d168f4d209e16518b5968c27f swapped `UserInfoRefreshInterval` from an `Integer` to a `Pattern` that was (string representations of numbers) || (some magic strings).  This breaks configs that had integers in play.
#2569
> Update types/oidcsettings UserInfoRefreshInterval to allow Integers again

- metadata.json
- spec/acceptance/mod_php_spec.rb
- spec/classes/mod/php_spec.rb
> (CAT-2100) Add Debian 12 support

- README.md
The License entry in the TOC of the README is not a link.
Let's fix that.
> fix license entry in the toc not being a link

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_proxy_protocol.epp
The module currently support configuring RemoteIP PROXY Protocol at the
system level, but the settings can also be used for specific virtual
hosts.
Allow to set `RemoteIPProxyProtocol` and `RemoteIPProxyProtocolExceptions`
at the VHost level.  For cosistency, une the same parameter names and
types as the ones used for mod_remoteip configuration.
> Allow configuring RemoteIPProxyProtocol at VHost level

- REFERENCE.md
- manifests/mod/security.pp
- manifests/params.pp
- spec/classes/mod/security_spec.rb
- templates/mod/security.conf.epp
Adds a parameter to set the audit log format to `JSON`
https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#user-content-SecAuditLogFormat
Since as of the current version of ModSecurity, this can only have two values `Native` and `JSON`, and `Native` is default, I decided only add the line if someone specifically sets the value to `JSON`. This means it shouldn't touch any existing config, especially on versions where this parameter may not exist.
> Adding ModSecurity parameter for audit log format.

- manifests/vhost.pp
Fix mod_headers load for headers in directory
Issue #2590
> Fix mod_headers load for headers in directory #2590

- manifests/mod/prefork.pp
Fixes a warning:
manifests/mod/prefork.pp - WARNING: there should be a single space before '=>' on line 97, column 17 on line 97 (check: space_before_arrow)
Add any additional context about the problem here.
Caused in cedd45b63be8.
> Correct whitespace in arrow alignment

- manifests/params.pp
- spec/classes/mod/http2_spec.rb
In EL8 httpd had a hard requirement on mod_http2 but in EL9 it turned into a weak dependency. While most installs default to installing weak dependencies, it can be disabled by users (by setting `install_weak_deps=0` in `/etc/dnf/dnf.conf`). OracleLinux even defaults to disabled.
EL7 doesn't have http2 at all so the whole class can't be used with it.
Add any additional context about the problem here.
Still a draft, but having a PR makes it easy for me to test.
> Install mod_http2 on EL if required
