- manifests/version.pp
- spec/acceptance/version.rb
noticed on a Debian/jessie system
> fix apache_version for Debian >7

- README.passenger.md
- manifests/params.pp
- spec/acceptance/mod_passenger_spec.rb
- spec/classes/mod/passenger_spec.rb
- templates/mod/passenger.conf.erb
Tested with Puppet master 3.7 and Foreman under mod_passenger.
> add passenger support for Debian/jessie

- manifests/init.pp
- manifests/mod/alias.pp
- manifests/params.pp
- spec/classes/mod/alias_spec.rb
https://tickets.puppetlabs.com/browse/MODULES-1554
> MODULES-1554: update error docs and icons path for RHEL7-based systems

- templates/vhost/_directories.erb
They were already being sorted in templates/vhost/_php*.erb, but not in
templates/vhost/_directories.erb
> MODULES-1680 - sort php_* hashes for idempotency

- manifests/mod/alias.pp
Introduced in #950 
https://github.com/puppetlabs/puppetlabs-apache/commit/7511cdaeaba8adc9afbadfaa60d65fe77abccdfa#commitcomment-9323711
> fix versioncmp test in mod::alias

- README.md
- manifests/mod/security.pp
- manifests/security/rule_link.pp
- templates/mod/security_crs.conf.erb
Add additional configuration options to mod_security
Ensure directories are purged to prevent duplicate definitions
> add configuration options to mod_security

- DESIGN.md
As discussed with @igalic at the contributor summit.
> Auto-tuning performance parameters

- metadata.json
https://www.dropbox.com/s/ky0qxt5n2wczqyi/Screenshot%202015-02-06%2013.18.38.png?dl=0
> Fix license for forge linting.

- spec/acceptance/mod_suphp_spec.rb
Add a sleep in the suphp test to allow things to start up properly
> FM-2140 - Fix for suphp test

- README.md
- manifests/custom_config.pp
- manifests/vhost.pp
- spec/acceptance/custom_config_spec.rb
- spec/acceptance/vhost_spec.rb
Fixes puppetlabs/puppetlabs-apache#928
> Fixup 928 - optionally omit priority

- README.md
- manifests/mod/auth_cas.pp
- manifests/params.pp
- spec/classes/mod/auth_cas_spec.rb
- templates/mod/auth_cas.conf.erb
Add support to configure mod_auth_cas within Apache.
> Add support for mod_auth_cas module configuration

- README.md
> Fixed vhost proxy_pass params documentation

- README.md
- manifests/default_mods.pp
- manifests/mod/authn_file.pp
- manifests/mod/authz_default.pp
- manifests/mod/authz_user.pp
> Allow includes necessary for basic authentication

- README.md
- manifests/mod/alias.pp
- spec/classes/mod/alias_spec.rb
- templates/mod/alias.conf.erb
> make icons directorylisting configurable

- README.md
- manifests/mod/remoteip.pp
- spec/classes/mod/remoteip_spec.rb
- templates/mod/remoteip.conf.erb
Add mod_remoteip module, fixing some issues on #989 that @mhaskel pointed out
> Remoteip module

- README.md
- manifests/mod/expires.pp
- spec/classes/mod/expires_spec.rb
- templates/mod/expires.conf.erb
allow global configuration of all of mod_expires Parameters.
> add parameters to configure expires globally

- README.md
fix syntax on examples of codes from README.
> fix syntax of code examples

- manifests/default_mods.pp
- manifests/init.pp
- manifests/mod.pp
- manifests/mod/alias.pp
- manifests/mod/prefork.pp
- manifests/mod/worker.pp
- manifests/mpm.pp
- manifests/params.pp
- manifests/version.pp
Add just about enough support to have a working compilation, basic install of Apache.
Installing and managing a vhost has been tested.
Signed-off-by: Christophe Vanlancker <christophe.vanlancker@inuits.eu>
> Add basic initial support for SLES 11

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_filters.erb
- tests/vhost_filter.pp
This adds support for specifying filters in an apache::vhost.
> apache::vhost filter support

- README.md
- manifests/mod/disk_cache.pp
- spec/classes/mod/disk_cache.rb
- templates/mod/disk_cache.conf.erb
Expanding on the initial PR by @dteirney (#1037) - Adding support to mod_disk_cache for >= 2.4
> Adding support to mod_disk_cache for >= 2.4

- manifests/mod/worker.pp
- spec/classes/mod/worker_spec.rb
- templates/mod/worker.conf.erb
This change adds the ListenBacklog option for the worker module.
> Add ListenBacklog for mod worker (MODULES-2432)

- README.md
See https://github.com/puppetlabs/puppetlabs-apache/commit/2dbb1ec540e71fb2f920891d213d88774faf5c14#diff-60ae41fd0a31977447947f59940ee9a4R31
> The purge_vhost_configs parameter is actually called purge_vhost_dir

- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
Add SLES/Suse support to mod::ssl.
> MODULES-2513 mod::ssl fails on SLES

- templates/mod/security.conf.erb
> (MODULES-2622) add SecUploadDir parameter to support file uploads with mod_security

- README.md
- manifests/init.pp
- manifests/params.pp
- templates/httpd.conf.erb
> Add option to configure the include pattern for the vhost_enable dir

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_docroot.erb
This amends #1222 to add a little bit of test coverage
> (MODULES-2120) Allow empty docroot

- spec/spec_helper.rb
See Jira ticket for the motivation for this change.
> (MODULES-2813) Fix deprecation warning in spec_helper.rb

- spec/classes/service_spec.rb
See Jira ticket for the motivation for this change.
> (MODULES-2812) Fix deprecation warning in service_spec.rb

- spec/classes/mod/auth_mellon_spec.rb
- spec/classes/mod/ext_filter_spec.rb
- spec/classes/mod/info_spec.rb
- spec/classes/mod/shib_spec.rb
- spec/unit/provider/a2mod/gentoo_spec.rb
- spec/unit/puppet/parser/functions/bool2httpd_spec.rb
See the Jira ticket for info on the motivation for this change.
> (MODULES-2811) Add missing helper lines to spec files

- spec/classes/dev_spec.rb
- spec/classes/mod/passenger_spec.rb
Small update to fix 2 warnings due to some duplicate entries.
> (MODULES-2773) Duplicate Entries in Spec Files

- templates/mod/nss.conf.erb
After changing variable nss_port to port in manifest file I did not changed port variable on "VirtualHost" line. Fixed
> changed typo

- manifests/init.pp
- manifests/mod/itk.pp
- manifests/mpm.pp
- spec/acceptance/itk_spec.rb
- spec/classes/mod/itk_spec.rb
> (MODULES-2200, MODULES-2865) fix ITK configuration on Ubuntu

- spec/spec_helper_acceptance.rb
> Make sure snake-oil certs are installed for beaker

- spec/acceptance/vhost_spec.rb
> Fix typo with versioncmp

- spec/acceptance/vhost_spec.rb
> Limit fastcgi testing to Debian osfamily

- spec/acceptance/vhost_spec.rb
For both Debian and older versions of Ubuntu, non-default repos are required to install the libapache2-mod-fastcgi package. I think the previous code worked on Ubuntu trusty, because in newer versions of Ubuntu, multiverse is enabled by default (according to the interwebs).
> (maint) fixes the fastcgi test for debian and older ubuntu releases

- manifests/vhost.pp
- templates/vhost/_redirect.erb
as per apache documentation
http://httpd.apache.org/docs/2.2/mod/mod_alias.html#redirectmatch
> allow status code on redirect match to be optional and not a requirement

- spec/acceptance/mod_php_spec.rb
- templates/vhost/_php.erb
Ensure php_values with a string type as a value get quoted.
> MODULES-3020 - quote php_values when the value is a string

- README.md
Needs review, then I can squash and merge.
This PR adds defaults, updates numerous links, adjusts formatting and style, and makes a few edits to text.
> 1.8.x README revisions

- README.md
- templates/vhost/_directories.erb
This allows specifying the mellon_sp_metadata_file parameter
> Add mellon_sp_metadata_file parameter for directory entries

- README.md
- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_passenger.erb
Add support for specifying PassengerUser in vhost for sandboxing application process
> (#3139) Add support for PassengerUser

- spec/classes/mod/dev_spec.rb
> MODULES-3211: fix broken strict_variable tests

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
attempt to add feature request as described at https://tickets.puppetlabs.com/browse/MODULES-1352
includes rspec tests
> MODULES-1352 : Better support for Apache 2.4 style require directives implementation

- manifests/mod/info.pp
- templates/mod/info.conf.erb
Changes lifted from Eric Young's feture request.
> (MODULES-3274) mod-info: specify the info_path

- manifests/mod/proxy_wstunnel.pp
- spec/classes/mod/proxy_wstunnel.rb
This adds minimal tests on top of #1462
> Add apache::mod::proxy_wstunnel and tests

- CHANGELOG.md
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> (maint) Fix a typo in CHANGELOG formatting

- CHANGELOG.md
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> (maint) Fix a typo in CHANGELOG: compatibilty

- README.md
> MODULES-3689 - change case

- templates/mod/security_crs.conf.erb
This effectively add the real_ip variable (and anomaly_score, sql_injection_score, xss_score=0, inbound_anomaly_score, outbound_anomaly_score).
> Sync security_crs.conf with latest upstream

- README.md
- manifests/mod/passenger.pp
- spec/classes/mod/passenger_spec.rb
- templates/mod/passenger.conf.erb
PassengerMaxInstancesPerApp has been available [since version Passenger 3.0] (https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxinstancesperapp)
> mod_passenger: PassengerMaxInstancesPerApp option

- README.md
- manifests/init.pp
- manifests/params.pp
- templates/httpd.conf.erb
> The meier move error log to params

- README.md
- manifests/mod/proxy.pp
- templates/mod/proxy.conf.erb
> Allow the proxy_via setting to be configured

- manifests/mod/security.pp
Adding requirement for httpd package to $modsec_dir file resource to fix bug MODULES-3985
> Adding requirement for httpd package

- README.md
- manifests/mod/passenger.pp
- templates/mod/passenger.conf.erb
Support parameter PassengerDataBufferDir on the passenger module manifest and template.
> Support parameter PassengerDataBufferDir

- .gitignore
- Gemfile
https://github.com/puppetlabs/modulesync_configs/pull/102
> (MODULES-3631) msync Gemfile for 1.9 frozen strings

- manifests/mod/rpaf.pp
Enable usage of different rpaf.conf file (e.g. rpaf forks 0.6.1
https://github.com/gnif/mod_rpaf)
> Add rpaf.conf template parameter

- README.md
- manifests/mod/ssl.pp
- spec/classes/mod/ssl_spec.rb
- templates/mod/ssl.conf.erb
- templates/vhost/_ssl.erb
Was already possible on vhost level, now also on server-level (overridable on vhost level)
> Add ability to set SSLStaplingReturnResponderErrors on server level

- spec/defines/vhost_spec.rb
Spec test added for #1569 
cc/ @EmersonPrado
> (MODULES-4213) Adds spec test for rewrite_inherit

- locales/puppetlabs-apache.pot
This is adding a POT file for the module.
> (FM-6116) - Adding POT file for metadata.json

- templates/vhost/_directories.erb
Regression from 86b2df3ebfc894184f4f0b206c3905d182037d23
> Fix alignement in vhost.conf

- README.md
- manifests/init.pp
As discussed in https://tickets.puppetlabs.com/browse/MODULES-4646
> Added supplementary_groups to the user resource

- metadata.json
Fixing Issue MODULES-4824 (https://tickets.puppetlabs.com/browse/MODULES-4824)
> MODULES-4824: Update the version compatibility to >= 4.7.0 < 5.0.0

- examples/vhost.pp
single_quote_string_with_variables:ERROR:single quoted string containing a variable found
> Fix single quoted string

- templates/vhost/_require.erb
fix vhost template file causing unexpected tIDENTIFIER
> Fix vhost template

- manifests/mod/proxy_html.pp
> Account for Suse osfamily for proxy_html module

- README.md
added entry in README for mod_nss module
> (MODULES-2808) documented mod_nss

- README.md
- manifests/mod/wsgi.pp
- spec/classes/mod/wsgi_spec.rb
- templates/mod/wsgi.conf.erb
Because this option is not available on all platform, it's not set in
the wsgi mod configuration by default.
> Add WSGIRestrictEmbedded to apache::mod::wsgi

- templates/vhost/_directories.erb
ProxyPass according to the https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass is an available directive in the Location context
> Add proxy_pass in directory template for location context

- README.md
Familiarizing myself with Apache and came across a few minor changes for docs. 
Putting default and boolean on separate lines.
> (maint) - Updating format of Doc

- README.md
Removes the testing section and any references to it
Adds a link to the CONTRIBUTING.md file
> (MODULES-2765) removes testing section

- spec/acceptance/custom_config_spec.rb
Currently there is a failure related to the logic of the test. The logic has been updated.
> (FM-6583) - Update test

- spec/spec_helper_acceptance.rb
Updating to reflect change in Bolt:
https://github.com/puppetlabs/bolt/pull/129/files
> Update modules to modulepath

- lib/facter/apache_version.rb
Was causing an error on Facter using AIX 6.1
https://puppetlabs.zendesk.com/agent/tickets/28413
> #puppethack Confined to Linux only

- README.md
- templates/vhost/_directories.erb
This adds the ability to specify session length. (See https://github.com/UNINETT/mod_auth_mellon for details.)
> Add ability to specify MellonSessionLength/mellon_session_length

- README.md
- manifests/mod/data.pp
- spec/classes/mod/data_spec.rb
ref: https://httpd.apache.org/docs/2.4/mod/mod_data.html
> Support mod_data

- README.md
- spec/defines/vhost_spec.rb
- templates/vhost/_directories.erb
Added limit_except support, based on the master branch, but for the puppet 3 compatible branch.
> Added limit_except support

- README.md
- manifests/mod/disk_cache.pp
- spec/classes/mod/disk_cache_spec.rb
- templates/mod/disk_cache.conf.erb
https://httpd.apache.org/docs/2.2/mod/mod_cache.html#cacheignoreheaders
http://blog.futtta.be/2011/02/23/3-apache-mod_cache-gotchas/
> added option to include CacheIgnoreHeaders for disk_cache module

- manifests/vhost.pp
- spec/acceptance/mod_dav_svn_spec.rb
- spec/acceptance/vhost_spec.rb
"Fixing" the sles facts may in fact break things.
> Don't test shib on Debian 7; fix incorrect facts

- manifests/params.pp
subversion-server          | Apache server module for Subversion server
> (maint) Add dav_svn packages for sles

- CHANGELOG.md
- metadata.json
- spec/classes/mod/jk_spec.rb
Also includes small rubocop fix.
> 3.0.0 Pre Release

- CHANGELOG.md
This should also reflect our internal documentation style.
- Document all parameters, classes, defines, facts, & functions as API.
- The three changelog sections are "Changed" for breaking changes, "Added" for features, and "Fixed" for bugfixes, in that order.
- Changes irrelevant to end users (such as .gitignore changes or .travis.yml changes) need not be mentioned.
- Changelogs should follow README style and convention where code formatting is concerned.
> Update changelog to reflect http://keepachangelog.com/

- CHANGELOG.md
- metadata.json
Pre Release to prepare for a clean release intended to precede a larger backwards incompatible release.
> (FM-7122) - 3.2.0 PreRelease

- manifests/mod/php.pp
- manifests/version.pp
> fixes for OpenSUSE ans SLES

- .gitignore
- .pdkignore
- .rubocop.yml
- .rubocop_todo.yml
- .travis.yml
- Gemfile
- Rakefile
- metadata.json
- spec/acceptance/mod_suphp_spec.rb
- spec/default_facts.yml
- spec/spec_helper.rb
pdk version: `1.7.0` 
pdk template ref: `1.7.0-0-g57412ed`
> pdksync - Update using 1.7.0

- templates/vhost/_wsgi.erb
root location alias must be defined last in order for others to work
> MODULES-7575 reverse sort the aliases

- README.md
> (maint) fixed typo

- README.md
Resolved broken link.
Also, added text for readability
> (maint) Broken link

- README.md
* added language identifier to code blocks
* bulleted some items
* decouple code blocks from sentence grammar
* use linked text instead of URL
> (maint) localizability fixes

- .fixtures.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- Rakefile
- metadata.json
- spec/default_facts.yml
(FM-7392) - Puppet 6 Testing Changes
pdk version: `1.7.0`
> pdksync - (FM-7392) - Puppet 6 Testing Changes

- .github_changelog_generator
- CHANGELOG.md
- metadata.json
Module Release Prep
pdk version: `1.7.0`
> pdksync - Module Release Prep 3.4.0

- templates/mod/proxy_html.conf.erb
Fixing syntax by adding newline, adding additional item for translation
> MODULES-7379: Fixing syntax by adding newline

- readmes/README_ja_JP.md
Creating this PR as translations have been put into the release branch. This will ensure they are also available in the master branch.
> (maint) - Put translation update into master

- README.md
- manifests/mod/wsgi.pp
- spec/classes/mod/wsgi_spec.rb
- templates/mod/wsgi.conf.erb
- templates/vhost/_wsgi.erb
Added two "per server" WSGI Options
* WSGIApplicationGroup
* WSGIPythonOptimize
including tests and little documentation in README.md
In addition two small cosmetic changes:
* some spaces
* a little header for the vhost wsgi configuration block
> Added WSGI Options WSGIApplicationGroup and WSGIPythonOptimize

- README.md
Running Tests section no longer exists therefore this is a dead link that goes nowhere. Removing to clean this up.
> (maint) - Removing dead link

- README.md
This commit contains minor edits to the README.
> (MODULES-8837) DOCS Release Review

- manifests/mod/ldap.pp
- spec/classes/mod/ldap_spec.rb
- templates/mod/ldap.conf.erb
Add ldap_path parameter to apache::mod::ldap with
Change ldap.conf.erb to use new parameter
Add new parameter to README.md
> MODULES-9003 Parameterize location for ldap-status

- manifests/mpm.pp
- manifests/mpm/disable_mpm_event.pp
- spec/classes/apache_spec.rb
fixes https://tickets.puppetlabs.com/browse/MODULES-8903
> Remove event mpm when using prefork, worker or itk

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> (MODULES-9867) - Release Merge back v5.1.0

- manifests/mpm.pp
- manifests/mpm/disable_mpm_worker.pp
Fixes: https://tickets.puppetlabs.com/browse/MODULES-9948
> Disable worker, when using prefork mpm

- spec/acceptance/vhost_spec.rb
> (maint) FM-8656 minor fix for sles

- metadata.json
- provision.yaml
> (FM-8672) - Addition of Support for CentOS 8

- .github/workflows/release.yml
> Add Github Actions release workflow

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> (maint) Release Mergeback version v5.3.0

- .github/workflows/weekly.yml
- .travis.yml
- spec/classes/mod/php_spec.rb
Add weekly scheduled workflows
pdk version: `1.16.0`
> pdksync - Add weekly scheduled workflows

- Gemfile
Reverts puppetlabs/puppetlabs-apache#2013
> Revert "(maint) Lock facter version < 4"

- templates/mod/proxy.conf.erb
> Fix template conditional

- metadata.json
- provision.yaml
https://tickets.puppetlabs.com/browse/IAC-727
> Disable testing on Redhat5 and Centos5

- .github/workflows/release.yml
- .github/workflows/weekly.yml
- .sync.yml
- .travis.yml
- manifests/params.pp
- metadata.json
- provision.yaml
- spec/acceptance/mod_php_spec.rb
- spec/defines/fastcgi_server_spec.rb
- spec/defines/vhost_spec.rb
> (IAC-746) - Add ubuntu 20.04 support

- README.md
- REFERENCE.md
- manifests/mod/ldap.pp
> Fix typos including consecutive occurrences of 'the'

- REFERENCE.md
- manifests/mod/alias.pp
- manifests/mod/autoindex.pp
- manifests/params.pp
- spec/classes/mod/alias_spec.rb
- templates/mod/alias.conf.erb
- templates/mod/autoindex.conf.erb
Allow replacing the default `/icons/` path with a custom path for the icons.
> Change icon path

- manifests/vhost.pp
- spec/classes/mod/auth_cas_spec.rb
`CASCookiePath` can be set in vhosts
> Add cas_cookie_path in vhosts

- .github/workflows/auto_release.yml
- .github/workflows/nightly.yml
- .github/workflows/pr_test.yml
- .github/workflows/release.yml
- .github/workflows/spec.yml
- .pdkignore
- .sync.yml
- .travis.yml
- metadata.json
PDK Update - Replace Travis and Appveyor with Github Actions
pdk version: `1.18.1`
> pdksync - PDK Update - Replace Travis and Appveyor with Github Actions

- .gitignore
- .gitpod.yml
- .pdkignore
- metadata.json
(maint) Running pdk update
pdk version: `2.0.0`
> pdksync - (maint) Running pdk update

- CHANGELOG.md
- metadata.json
> (maint) Release Prep v6.3.1

- CHANGELOG.md
- metadata.json
> (maint) Release Merge Back PR v6.3.1

- CHANGELOG.md
- metadata.json
Nightly Results
https://github.com/puppetlabs/puppetlabs-apache/actions/runs/1088429756
> (maint) Release Prep v6.4.0

- .sync.yml
- Rakefile
Adding the changes back to module which was overwritten with pdksync
https://github.com/puppetlabs/puppetlabs-apache/pull/2148
> (maint) - Set max_issues for changelog generator to 500

- spec/classes/mod/passenger_spec.rb
- spec/classes/mod/php_spec.rb
See individual commits for details. This should have no impact on test coverage but it should make them more correct/easier to read.
> Various spec cleanups

- manifests/mod/suphp.pp
Fixes: 8716eb95a2123120f83cf67b1c86cfcae63f0852
> Restore Ubuntu 14.04 support in suphp

- metadata.json
- spec/classes/mod/fastcgi_spec.rb
- spec/classes/mod/php_spec.rb
(IAC-1751) - Add Support for Rocky 8
pdk version: `2.1.0`
> pdksync - (IAC-1751) - Add Support for Rocky 8

- metadata.json
- spec/classes/mod/fastcgi_spec.rb
- spec/classes/mod/php_spec.rb
- spec/spec_helper_acceptance_local.rb
(IAC-1753) - Add Support for AlmaLinux 8
pdk version: `2.1.0`
> pdksync - (IAC-1753) - Add Support for AlmaLinux 8

- spec/defines/vhost_spec.rb
The proxy_test_reverse_match parameter is now tested.
> Test proxy_dest_reverse_match parameter

- metadata.json
> Revert "(MAINT) Removing support for CentOS 8"

- Gemfile
- Rakefile
- metadata.json
pdksync/remove_puppet_module_gems
pdk version: `2.5.0`
> pdksync - (PDKSync) Removal of puppet_module_gems

- spec/acceptance/apache_parameters_spec.rb
- spec/acceptance/class_spec.rb
- spec/acceptance/vhost_spec.rb
- spec/setup_acceptance_node.pp
A commit to address forgotten selinux facts present in the acceptance test files.
> (Maint) Addressing Selinux legacy facts

- manifests/mod/remoteip.pp
Fixes: df6862a512f7b0ea0b551da97b2e3aca5762d441 ("Simplify data types and array handling")
> Fix remoteip data types

- templates/vhost/_directories.erb
This is the full list from https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html
Following the current style of CamelCase -> snake_case
> Add the missing mod_authnz_ldap parameters

- templates/mod/mpm_event.conf.epp
Fixes: ffbcb58023e5 ("(CAT-1346) erb_to_epp conversion for mod directory")
> Remove unused file templates/mod/mpm_event.conf.epp

- metadata.json
Fixing apache CI pipeline fix
N/A
> (MAINT) Fixing apache CI pipeline fix (removing unsupported OS)

- .sync.yml
- Gemfile
- Rakefile
- metadata.json
(MAINT) PDK Update
pdk version: `3.0.0`
> pdksync - (MAINT) PDK Update

- .fixtures.yml
> Cleanup .fixtures.yml

- spec/defines/vhost_spec.rb
> vhost_spec: test if whole catalog compiles

- manifests/vhost.pp
- spec/defines/vhost_spec.rb
- templates/vhost/_serveralias.epp
> Correct handling of $serveraliases as string
